// pages/api/review/duplicate-action.js
import pool from'../../../lib/db';
import{withOrg}from'../../../lib/apiHelpers';
import{detectDuplicates}from'../../../lib/duplicateDetector';
async function canonicalName(db,id,org){const q=await db.query(`SELECT id,display_name,first_name,last_name,phone,phone_numbers,metadata,living_truth,identity_verification_status FROM people WHERE id=$1 AND organization_id=$2 AND status='active' FOR UPDATE`,[id,org]);return q.rows[0]||null}
function nameOf(p){return String(p.display_name||[p.first_name,p.last_name].filter(Boolean).join(' ')||p.first_name||'').trim()}
function phoneList(p){const v=Array.isArray(p.phone_numbers)?p.phone_numbers:p.phone?[p.phone]:[];return[...new Set(v.filter(Boolean).map(x=>typeof x==='string'?x:x?.normalized||x?.raw||x?.phone).filter(Boolean))].slice(0,4)}
async function mergePeople(db,org,canonicalId,duplicateId,actorId,evidence){if(canonicalId===duplicateId)throw Object.assign(new Error('A person cannot be merged with themselves.'),{statusCode:400});const canonical=await canonicalName(db,canonicalId,org),duplicate=await canonicalName(db,duplicateId,org);if(!canonical||!duplicate)throw Object.assign(new Error('Both active people must still exist.'),{statusCode:404});const ordered=[String(canonicalId),String(duplicateId)].sort();await db.query(`SELECT id FROM people WHERE organization_id=$1 AND id=ANY($2::uuid[]) ORDER BY id FOR UPDATE`,[org,ordered]);
const tables=['attendance_records:people_id','participation_records:person_id','timeline_events:people_id','person_aliases:person_id','person_memory:person_id','aria_learning:person_id','aria_brain_feed:person_id','aria_conversations:person_id','aria_care_contexts:person_id','aria_actions:person_id','aria_observations:person_id','aria_events:person_id','care_feedback:person_id','intelligence_outcomes:person_id','person_memberships:person_id','person_roles:person_id','person_field_values:person_id','person_lifecycle:person_id','person_documents:person_id','person_tasks:person_id','person_communications:person_id','person_segment_members:person_id'];
for(const spec of tables){const[i,col]=spec.split(':');try{await db.query(`UPDATE ${i} SET ${col}=$1 WHERE ${col}=$2`,[canonicalId,duplicateId])}catch(err){throw Object.assign(new Error(`Could not safely move ${i} history: ${err.message}`),{statusCode:409})}}
try{await db.query(`UPDATE person_relationships SET person_id=CASE WHEN person_id=$1 THEN $2 ELSE person_id END,related_person_id=CASE WHEN related_person_id=$1 THEN $2 ELSE related_person_id END WHERE person_id=$1 OR related_person_id=$1`,[duplicateId,canonicalId])}catch(err){throw Object.assign(new Error(`Could not safely move relationships: ${err.message}`),{statusCode:409})}
try{await db.query(`DELETE FROM aria_person_state WHERE organization_id=$1 AND person_id=$2 AND EXISTS(SELECT 1 FROM aria_person_state x WHERE x.organization_id=$1 AND x.person_id=$3)`,[org,duplicateId,canonicalId]);await db.query(`UPDATE aria_person_state SET person_id=$1 WHERE organization_id=$2 AND person_id=$3`,[canonicalId,org,duplicateId])}catch(err){throw Object.assign(new Error(`Could not safely merge ARIA state: ${err.message}`),{statusCode:409})}
const mergedPhones=[...new Set([...phoneList(canonical),...phoneList(duplicate)])].slice(0,2),phoneJson=JSON.stringify(mergedPhones.map((p,i)=>({raw:p,normalized:p,source:'identity_merge',index:i+1})));const mergedMetadata={...(canonical.metadata||{}),identity_verified:true,last_identity_merge:{duplicate_id:duplicateId,merged_at:new Date().toISOString(),merged_by:actorId,evidence},};const truth={...(canonical.living_truth||{}),status:'alive',source:'human_review',confirmed_at:(canonical.identity_verified_at||new Date().toISOString()),confirmed_by:(canonical.identity_verified_by||actorId)};await db.query(`UPDATE people SET phone=$2,phone_numbers=$3,identity_verification_status='verified',identity_verified_at=COALESCE(identity_verified_at,NOW()),identity_verified_by=COALESCE(identity_verified_by,$4),identity_verification_source=COALESCE(identity_verification_source,'human_review'),metadata=$5,living_truth=$6,updated_at=NOW() WHERE id=$1 AND organization_id=$7`,[canonicalId,mergedPhones[0]||null,phoneJson,actorId,mergedMetadata,truth,org]);await db.query(`UPDATE people SET status='archived',quarantine_reason=NULL,living_truth=jsonb_build_object('status','archived','source','identity_merge','merged_into',$2::text,'merged_at',NOW(),'merged_by',$3::text),metadata=metadata||jsonb_build_object('identity_merged_into',$2::text,'identity_merged_at',NOW(),'identity_merged_by',$3::text),updated_at=NOW() WHERE id=$1 AND organization_id=$4`,[duplicateId,canonicalId,actorId,org]);await db.query(`INSERT INTO identity_pair_decisions(organization_id,person_a_id,person_b_id,decision,decided_by,evidence,updated_at) VALUES($1,$2,$3,'duplicate_merged',$4,$5,NOW()) ON CONFLICT(organization_id,LEAST(person_a_id,person_b_id),GREATEST(person_a_id,person_b_id)) DO UPDATE SET decision='duplicate_merged',decided_by=EXCLUDED.decided_by,evidence=EXCLUDED.evidence,updated_at=NOW()`,[org,canonicalId,duplicateId,actorId,evidence]);return{canonical,duplicate}}
export default withOrg(async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const{action,canonicalId,duplicateId}=req.body||{};if(!['merge','keep_separate'].includes(action)||!canonicalId||!duplicateId)return res.status(400).json({error:'Invalid duplicate decision.'});const db=await pool.connect();try{await db.query('BEGIN');const ids=[String(canonicalId),String(duplicateId)].sort();await db.query(`SELECT id FROM people WHERE organization_id=$1 AND id=ANY($2::uuid[]) AND status='active' ORDER BY id FOR UPDATE`,[req.org.id,ids]);const audit=await detectDuplicates(req.org.id);const pair=audit.duplicates.find(x=>new Set([String(x.left.id),String(x.right.id)]).size===2&&[x.left.id,x.right.id].includes(canonicalId)&&[x.left.id,x.right.id].includes(duplicateId));if(!pair){await db.query('ROLLBACK');return res.status(409).json({error:'This duplicate decision is no longer supported by current evidence.',code:'DUPLICATE_STALE'})}const evidence={score:pair.score,status:pair.status,evidence:pair.evidence,method:pair.method,detector_version:audit.detector_version};if(action==='keep_separate'){await db.query(`INSERT INTO identity_pair_decisions(organization_id,person_a_id,person_b_id,decision,decided_by,evidence,updated_at) VALUES($1,$2,$3,'not_duplicate',$4,$5,NOW()) ON CONFLICT(organization_id,LEAST(person_a_id,person_b_id),GREATEST(person_a_id,person_b_id)) DO UPDATE SET decision='not_duplicate',decided_by=EXCLUDED.decided_by,evidence=EXCLUDED.evidence,updated_at=NOW()`,[req.org.id,canonicalId,duplicateId,req.user.id,evidence]);await db.query('COMMIT');return res.status(200).json({ok:true,action:'kept_separate'})}await mergePeople(db,req.org.id,canonicalId,duplicateId,req.user.id,evidence);await db.query('COMMIT');return res.status(200).json({ok:true,action:'merged',canonical_id:canonicalId,archived_id:duplicateId})}catch(err){try{await db.query('ROLLBACK')}catch{}console.error('[DUPLICATE] Action error:',err);return res.status(err.statusCode||500).json({error:err.statusCode?err.message:'Duplicate action could not be completed.',code:err.code})}finally{db.release()}});
