// pages/api/review/index.js
import pool from'../../../lib/db';
import{withOrg}from'../../../lib/apiHelpers';
import{detectDuplicates}from'../../../lib/duplicateDetector';
function nameOf(x){return String(x.display_name||[x.first_name,x.last_name].filter(Boolean).join(' ')||x.first_name||'').trim()}
function phones(x){const v=Array.isArray(x?.phones)?x.phones:x?.phone?[x.phone]:[];return[...new Set(v.map(p=>typeof p==='string'?p:p?.normalized||p?.raw||p?.phone).filter(Boolean))]}
export default withOrg(async function handler(req,res){if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});try{const audit=await detectDuplicates(req.org.id);const groups=audit.groups.map(g=>{const ordered=[...g.members].sort((a,b)=>Number(b.verified)-Number(a.verified)||String(a.name).localeCompare(String(b.name)));const anchor=ordered[0],others=ordered.slice(1);return{id:`db:${g.id}`,kind:'database_duplicate',name:others.length?`${anchor.name} · ${others[0].name}`:anchor.name,first_name:anchor.name,last_name:'',phone:anchor.phone,phones:anchor.phones,type:'person',status:g.status,reason:g.reason,suggestion:'Compare the records. Merge only when the evidence belongs to one person; otherwise keep them separate.',score:g.score,candidates:g.members.map(m=>({id:m.id,name:m.name,phone:m.phone,phones:m.phones,score:g.score,verified:m.verified,verification_status:m.verification_status})),verified_ids:g.members.filter(m=>m.verified).map(m=>m.id),group:g.members,duplicate_evidence:g.evidence,detector_version:audit.detector_version,created_at:null,updated_at:null}});
const{rows}=await pool.query(`SELECT id,first_name,last_name,display_name,phone,phone_numbers,type,quarantine_reason,last_scan_job_id,living_truth,metadata,identity_verification_status,identity_verified_at,created_at,updated_at FROM people WHERE organization_id=$1 AND status='active' AND living_truth->>'status' IN ('needs_decision','conflict') AND jsonb_array_length(COALESCE(metadata->'candidate_ids','[]'::jsonb))>0 ORDER BY updated_at DESC,created_at DESC`,[req.org.id]);const ids=[...new Set(rows.flatMap(x=>Array.isArray(x.metadata?.candidate_ids)?x.metadata.candidate_ids:[]).map(String))],live=ids.length?(await pool.query(`SELECT id,first_name,last_name,display_name,phone,phone_numbers,type,identity_verification_status FROM people WHERE organization_id=$1 AND status='active' AND id=ANY($2::uuid[])`,[req.org.id,ids])).rows:[],byId=new Map(live.map(x=>[String(x.id),x]));const pending=rows.map(x=>{const ids2=Array.isArray(x.metadata?.candidate_ids)?x.metadata.candidate_ids.map(String):[],stored=Array.isArray(x.metadata?.candidate_details)?x.metadata.candidate_details:[],resolved=stored.length?stored:ids2.map(id=>{const c=byId.get(id);return c?{id:c.id,name:nameOf(c),phone:c.phone,phones:phones(c),verified:c.identity_verification_status==='verified'}:null}).filter(Boolean);return{id:`scan:${x.id}`,source_review_id:x.id,kind:'scan_duplicate',name:nameOf(x),first_name:x.first_name,last_name:x.last_name,phone:x.phone,phones:x.phone_numbers||[],type:x.type,status:x.living_truth?.status||'needs_decision',reason:'ARIA found a possible duplicate in a scanned record.',suggestion:'Check the scanned row against the proposed existing person, then Merge or create a New person.',raw_name:x.metadata?.raw_name||null,raw_phones:x.metadata?.raw_phones||[],row_number:x.metadata?.row_number??null,scan_job_id:x.last_scan_job_id,candidate_ids:ids2,candidates:resolved,created_at:x.created_at,updated_at:x.updated_at}});
const merged=[...pending,...groups].sort((a,b)=>(b.score||0)-(a.score||0));return res.status(200).json({items:merged,total:merged.length,people_count:audit.people_count,verified_count:audit.verified_count,unverified_count:audit.unverified_count,detector_version:audit.detector_version})}catch(err){console.error('[REVIEW] List error:',err);return res.status(500).json({error:'Review Center could not load.'})}});
