// pages/api/people.js
import pool from'../../lib/db';
import{normalizePhone}from'../../lib/phoneUtils';
import{normalizeDisplayName}from'../../lib/scanValidation';
import{withOrg}from'../../lib/apiHelpers';
import{emitAriaEvent}from'../../lib/aria/eventEmitter';
import{processAriaEvent}from'../../lib/aria/eventProcessor';
const splitName=value=>{const n=normalizeDisplayName(value),parts=n.core.split(/\s+/).filter(Boolean);return{first_name:parts.shift()||'',last_name:parts.join(' '),display_name:n.display}}
async function duplicatePhone(orgId,phone,excludeId=null){if(!phone)return null;const q=await pool.query(`SELECT id,display_name,phone FROM people WHERE organization_id=$1 AND status='active' AND living_truth->>'status' NOT IN ('needs_decision','conflict') AND id<>COALESCE($2::uuid,'00000000-0000-0000-0000-000000000000') AND (phone=$3 OR EXISTS(SELECT 1 FROM jsonb_array_elements(COALESCE(phone_numbers,'[]'::jsonb)) v WHERE v->>'normalized'=$3)) LIMIT 1`,[orgId,excludeId,phone]);return q.rows[0]||null}
async function handler(req,res){const orgId=req.org.id;
if(req.method==='GET'){try{const{rows}=await pool.query(`SELECT p.*,em.last_seen AS last_attended_date,lc.last_contacted FROM people p LEFT JOIN engagement_metrics em ON em.person_id=p.id AND em.organization_id=p.organization_id LEFT JOIN LATERAL(SELECT occurred_at AS last_contacted FROM person_communications pc WHERE pc.person_id=p.id AND pc.organization_id=p.organization_id ORDER BY occurred_at DESC NULLS LAST,created_at DESC LIMIT 1)lc ON TRUE WHERE p.organization_id=$1 AND COALESCE(p.status,'active')='active' AND p.living_truth->>'status' NOT IN ('needs_decision','conflict') ORDER BY COALESCE(NULLIF(p.display_name,''),NULLIF(TRIM(CONCAT_WS(' ',p.first_name,p.last_name)),''),p.first_name) ASC`,[orgId]);return res.status(200).json(rows)}catch(err){console.error('GET people error:',err);return res.status(500).json({error:'Unable to load people.'})}}
if(req.method==='POST'){const body=req.body||{},name=String(body.full_name||'').trim();let first_name=String(body.first_name||'').trim(),last_name=String(body.last_name||'').trim(),display_name='';if(!first_name&&name){const split=splitName(name);first_name=split.first_name;last_name=split.last_name;display_name=split.display_name}else display_name=[first_name,last_name].filter(Boolean).join(' ');if(!first_name)return res.status(400).json({error:'A name is required'});if(first_name.length>150||last_name.length>150)return res.status(400).json({error:'Name is too long'});const phone=normalizePhone(body.phone);try{const duplicate=await duplicatePhone(orgId,phone);if(duplicate)return res.status(409).json({error:'That full phone number already belongs to another person.',code:'DUPLICATE_ACTIVE_PERSON',person:duplicate});const person=(await pool.query(`INSERT INTO people(organization_id,first_name,last_name,display_name,phone,email,type,birthday,created_by,living_truth,status,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'active','manual') RETURNING *`,[orgId,first_name,last_name,display_name||null,phone,String(body.email||'').trim().toLowerCase()||null,String(body.type||'visitor').trim()||'visitor',body.birthday||null,req.user.id,JSON.stringify({status:'alive',confidence:90,source:'canonical_record',updated_at:new Date().toISOString()})])).rows[0];try{const event=await emitAriaEvent({organizationId:orgId,personId:person.id,type:'PERSON_CREATED',source:'manual',actorId:req.user.id,metadata:{source:'api'},eventKey:`manual:${orgId}:person:${person.id}:created`});if(event)await processAriaEvent(event)}catch(err){console.error('ARIA person creation event failed:',err)}return res.status(201).json(person)}catch(err){console.error('POST person error:',err);return res.status(500).json({error:'Unable to create person.'})}}
if(req.method==='PUT'){const body=req.body||{},id=body.id;if(!id)return res.status(400).json({error:'id is required'});try{const check=await pool.query(`SELECT id FROM people WHERE id=$1 AND organization_id=$2 AND status='active' AND living_truth->>'status' NOT IN ('needs_decision','conflict') LIMIT 1`,[id,orgId]);if(!check.rows.length)return res.status(404).json({error:'Person not found'});let first_name=body.first_name,last_name=body.last_name,display_name; if(body.full_name!==undefined){const split=splitName(body.full_name);first_name=split.first_name;last_name=split.last_name;display_name=split.display_name}const updates=[],values=[];let n=1;if(first_name!==undefined){const v=String(first_name).trim();if(!v)return res.status(400).json({error:'Name cannot be empty'});if(v.length>150)return res.status(400).json({error:'Name is too long'});updates.push(`first_name=$${n++}`);values.push(v)}if(last_name!==undefined){updates.push(`last_name=$${n++}`);values.push(String(last_name||'').trim())}if(display_name!==undefined){updates.push(`display_name=$${n++}`);values.push(display_name||null)}if(body.phone!==undefined){const phone=normalizePhone(body.phone);const duplicate=await duplicatePhone(orgId,phone,id);if(duplicate)return res.status(409).json({error:'That full phone number already belongs to another person.',code:'DUPLICATE_ACTIVE_PERSON',person:duplicate});updates.push(`phone=$${n++}`);values.push(phone)}if(body.email!==undefined){updates.push(`email=$${n++}`);values.push(String(body.email||'').trim().toLowerCase()||null)}if(body.type!==undefined){updates.push(`type=$${n++}`);values.push(String(body.type||'visitor').trim()||'visitor')}if(body.birthday!==undefined){updates.push(`birthday=$${n++}`);values.push(body.birthday||null)}if(!updates.length)return res.status(400).json({error:'No fields to update'});updates.push('updated_at=NOW()');values.push(id,orgId);const person=(await pool.query(`UPDATE people SET ${updates.join(',')} WHERE id=$${n} AND organization_id=$${n+1} AND status='active' AND living_truth->>'status' NOT IN ('needs_decision','conflict') RETURNING *`,values)).rows[0];if(!person)return res.status(404).json({error:'Person not found'});try{const event=await emitAriaEvent({organizationId:orgId,personId:id,type:'PERSON_UPDATED',source:'manual',actorId:req.user.id,metadata:{updated_fields:Object.keys(body).filter(k=>k!=='id')},eventKey:`manual:${orgId}:person:${id}:update:${Date.now()}`});if(event)await processAriaEvent(event)}catch(err){console.error('ARIA person update event failed:',err)}return res.status(200).json(person)}catch(err){console.error('PUT person error:',err);return res.status(500).json({error:'Unable to update person.'})}}
res.setHeader('Allow','GET,POST,PUT');return res.status(405).json({error:'Method not allowed'})}
export default withOrg(handler);
