// lib/aiProviders/gemini.js
const URL='https://generativelanguage.googleapis.com/v1beta/interactions';
const key=()=>process.env.GEMINI_API_KEY||'';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function read(r){const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:{message:text.slice(0,1000)}}}return data}
export async function geminiRequest(body,{timeoutMs=90000,retries=1}={}){if(!key())return{response:new Response(JSON.stringify({error:{message:'Gemini is not configured.'}}),{status:401}),data:{error:{message:'Gemini is not configured.'}}};let last=null;for(let attempt=0;attempt<=retries;attempt++){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),timeoutMs);try{const response=await fetch(URL,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key()},body:JSON.stringify(body),signal:ac.signal});const data=await read(response);if(response.ok||![408,429,500,502,503,504].includes(response.status)||attempt===retries)return{response,data};last=Object.assign(new Error(data?.error?.message||`Gemini request failed (${response.status})`),{status:response.status,data});const retryAfter=Number(response.headers.get('retry-after'));await sleep(Number.isFinite(retryAfter)&&retryAfter>0?Math.min(retryAfter*1000,15000):1000*(attempt+1))}catch(e){last=e;if(attempt===retries)throw e}finally{clearTimeout(timer)}}throw last}
export const geminiConfigured=()=>Boolean(key());
export function geminiTextBody({input,responseFormat=null,thinkingLevel=process.env.GEMINI_THINKING_LEVEL||'low',previousInteractionId=null,tools=null}={}){const body={model:process.env.GEMINI_TEXT_MODEL||'gemini-3.8-flash',input,generation_config:{thinking_level:thinkingLevel}};if(responseFormat)body.response_format=responseFormat;if(previousInteractionId)body.previous_interaction_id=previousInteractionId;if(Array.isArray(tools)&&tools.length)body.tools=tools;return body}
export function geminiOutput(data){return data?.output_text||data?.steps?.slice?.().reverse?.().find?.(s=>s?.type==='model_output')?.content?.find?.(c=>typeof c?.text==='string')?.text||''}
