// lib/aria/draftEngine.js
import pool from'../db';import{generateText}from'../aiGateway';import{getLearnings}from'./learningEngine';
const clean=(v,max=3000)=>String(v??'').trim().slice(0,max),first=p=>clean(p.first_name||'there',80),attribution=n=>{const x=clean(n,160);return x?`From: ${x}`:'From: your church';},withAttribution=(message,name)=>{const body=clean(message,1500).replace(/\s*\n?\s*From:\s*.+$/i,'').trim();return `${body}\n\n${attribution(name)}`.slice(0,1600)};
function fallback(person,type){const n=first(person),x={welcome_and_onboard:`Hi ${n}, it was lovely having you with us. Just wanted to say you're remembered and welcome anytime.`,continue_onboarding:`Hi ${n}, just checking in to see how you're doing. We're glad to have you with us and would love to stay connected.`,thoughtful_check_in:`Hi ${n}, just wanted to say hello and see how things are going with you. Hope you're doing well.`,strengthen_relationship:`Hi ${n}, just wanted to say hello and let you know we appreciate having you with us.`,adjust_care_approach:`Hi ${n}, I wanted to check in personally and see how you're doing. I'd really value hearing how things have been for you.`};return x[type]||x.thoughtful_check_in;}
export async function createCareDraft({organizationId,personId,actionId=null,actionType='thoughtful_check_in',actorId=null}){
 if(!organizationId||!personId)throw new Error('organizationId and personId are required');
 const[p,o,m,t,f,l,a]=await Promise.all([pool.query(`SELECT id,first_name,last_name,display_name,phone,phone_numbers,email,type FROM people WHERE id=$1 AND organization_id=$2 AND status='active' LIMIT 1`,[personId,organizationId]),pool.query(`SELECT name,aria_instructions FROM organizations WHERE id=$1 LIMIT 1`,[organizationId]),pool.query(`SELECT memory_type,content,importance,confidence FROM person_memory WHERE organization_id=$1 AND person_id=$2 AND active=true ORDER BY updated_at DESC LIMIT 8`,[organizationId,personId]),pool.query(`SELECT event_type,title,description,occurred_at FROM timeline_events WHERE people_id=$1 ORDER BY occurred_at DESC,created_at DESC LIMIT 8`,[personId]),pool.query(`SELECT feedback_type,sentiment,note,observed_at FROM care_feedback WHERE organization_id=$1 AND person_id=$2 ORDER BY observed_at DESC LIMIT 6`,[organizationId,personId]),getLearnings(organizationId,{personId,limit:10}),actionId?pool.query(`SELECT id,type,action_metadata,status FROM aria_actions WHERE id=$1 AND organization_id=$2 AND person_id=$3 LIMIT 1`,[actionId,organizationId,personId]):Promise.resolve({rows:[]})]);
 if(!p.rows.length)throw new Error('Person not found');if(actionId&&!a.rows.length)throw new Error('Action not found');if(actionId&&!['proposed','approved'].includes(a.rows[0].status))throw new Error(`Action is not available for drafting: ${a.rows[0].status}`);
 const person=p.rows[0],org=o.rows[0]||{},organizationName=clean(org.name,160),facts={person:clean(person.display_name||`${person.first_name||''} ${person.last_name||''}`),care_reason:clean(a.rows[0]?.action_metadata?.reason||'Intentional human care',500),memory:m.rows.map(x=>({type:x.memory_type,content:clean(x.content,400)})),history:t.rows.map(x=>({type:x.event_type,title:clean(x.title,160),description:clean(x.description,300),at:x.occurred_at})),feedback:f.rows.map(x=>({type:x.feedback_type,sentiment:x.sentiment,note:clean(x.note,300)})),learning:l.map(x=>({type:x.learning_type,key:x.learning_key,value:x.value}))};
 let message='';try{const r=await generateText({organizationId,purpose:'care_draft',maxTokens:140,temperature:.6,system:`You are ARIA inside NYEOCARE. Write one short warm human WhatsApp message. Use only supplied facts. Never mention AI, scores, monitoring, risk, attendance analytics, databases, or why the person was selected. Never invent personal facts. Never pressure the person. Do not add an organization name or sign-off; NYEOCARE will add the official organization attribution separately. Return only the message. Voice: ${clean(org.aria_instructions,1200)||'warm, respectful, personal and sincere.'}`,user:JSON.stringify(facts)});message=clean(r.text,1500)}catch{}if(!message)message=fallback(person,actionType);message=withAttribution(message,organizationName);
 const communication=(await pool.query(`INSERT INTO person_communications(organization_id,person_id,channel,direction,status,subject,content,metadata,created_by,occurred_at,created_at,updated_at)VALUES($1,$2,'whatsapp','outbound','draft','ARIA care draft',$3,$4,$5,NOW(),NOW(),NOW()) RETURNING *`,[organizationId,personId,message,{action_id:actionId,action_type:actionType,requires_human_approval:true,requires_human_send:true,organization_attribution:organizationName||'your church'},actorId])).rows[0];await pool.query(`INSERT INTO timeline_events(people_id,event_type,title,description,metadata,source,occurred_at,created_at)VALUES($1,'aria_draft','ARIA care draft',$2,$3,'aria',NOW(),NOW())`,[personId,message,{communication_id:communication.id,action_id:actionId}]);
 const rawPhone=person.phone||((Array.isArray(person.phone_numbers)&&person.phone_numbers[0])||null);return{message,communication,requiresHumanApproval:true,requiresHumanSend:true,whatsappUrl:rawPhone?`https://wa.me/${String(rawPhone).replace(/\D/g,'')}?text=${encodeURIComponent(message)}`:null};
}
