// lib/aria/participationGenerator.js
import pool from'../db';import{emitAriaEvent}from'./eventEmitter';import{processAriaEvent}from'./eventProcessor';import{updateEngagementMetricsForPerson}from'./engagementIntelligence';import{computeRelationshipScore}from'./relationshipScore';import{createObservation}from'./observationEngine';import{updatePersonState}from'./stateManager';import{planActionFromObservation}from'./recommendationEngine';
const returnDraft=(name,ctx)=>{const first=name||'there';if(ctx?.reason_note)return 'Welcome back, '+first+'. It was good to see you today. I hope things are going well with what kept you away.';if(ctx?.reason_code==='travel')return 'Welcome back, '+first+'. It is good to have you back. I hope the trip went well.';if(ctx?.reason_code==='work_school')return 'Welcome back, '+first+'. It is good to see you again. I hope work or school is going well.';if(ctx?.reason_code==='family')return 'Welcome back, '+first+'. It is good to see you again. I hope things are settling down well.';if(ctx?.reason_code==='health')return 'Welcome back, '+first+'. It is good to see you again. I hope you are doing well.';return 'Welcome back, '+first+'. It was good to see you today. Hope you had a good week.'};
async function handleReturnAfterAbsence({sessionId,orgId,personId}){
 const ctx=await pool.query('SELECT id,reason_code,reason_note,expected_return_date FROM aria_attendance_contexts WHERE organization_id=$1 AND person_id=$2 AND session_id<>$3 AND resolved_at IS NULL ORDER BY created_at DESC LIMIT 1',[orgId,personId,sessionId]);
 const obs=await pool.query('SELECT id FROM aria_observations WHERE organization_id=$1 AND person_id=$2 AND type=\'UNUSUAL_ABSENCE\' AND status=\'active\' ORDER BY detected_at DESC LIMIT 1',[orgId,personId]);
 if(!ctx.rows.length&&!obs.rows.length)return null;
 if(ctx.rows.length)await pool.query('UPDATE aria_attendance_contexts SET resolved_at=NOW() WHERE id=$1',[ctx.rows[0].id]);
 if(obs.rows.length)await pool.query('UPDATE aria_observations SET status=\'resolved\' WHERE id=$1',[obs.rows[0].id]);
 await pool.query('UPDATE aria_actions SET status=\'cancelled\',failure_reason=\'Person returned; previous absence follow-up is no longer pending.\',updated_at=NOW() WHERE organization_id=$1 AND person_id=$2 AND status IN(\'proposed\',\'approved\') AND action_metadata->>\'kind\'=\'first_session_check_in\'',[orgId,personId]);
 const person=await pool.query('SELECT first_name,last_name FROM people WHERE id=$1 AND organization_id=$2 LIMIT 1',[personId,orgId]);
 const name=[person.rows[0]?.first_name,person.rows[0]?.last_name].filter(Boolean).join(' ');
 const ctxRow=ctx.rows[0]||null,source='attendance:'+sessionId+':return:'+personId;
 const observationId=await createObservation({organizationId:orgId,personId,type:'RETURNED_AFTER_ABSENCE',confidence:1,severity:'low',urgency:'low',evidence:{sources:['attendance'],facts:['Person was recorded as present after a previous absence signal.'],inference:ctxRow?'The person returned after human-provided absence context.':'The person returned after a previous absence signal.',previous_context:ctxRow?{reason_code:ctxRow.reason_code,has_note:Boolean(ctxRow.reason_note),expected_return_date:ctxRow.expected_return_date}:null,session_id:sessionId},sourceEventId:source});
 const action=await planActionFromObservation({organizationId:orgId,personId,observationId,actionType:'SEND_MESSAGE',priority:'low',actionMetadata:{kind:'returned_after_absence',notify_organization:true,requires_human_approval:true,draft_required:true,channel:'whatsapp',personalized:Boolean(ctxRow),draft_message:returnDraft(name,ctxRow),summary:name+' is back after being away.',knowledge:ctxRow?'Human context was provided for the previous absence.':'ARIA only knows this person was previously absent.',suggestion:'Review the suggested personal welcome-back message.'},actionKey:'briefing:return_after_absence:'+sessionId+':'+personId});
 return action;
}


export async function generateParticipationFromSession(sessionId,orgId){
 if(!sessionId||!orgId)throw new Error('sessionId and orgId are required');
 const client=await pool.connect(),records=[];let sessionRow=null;
 try{await client.query('BEGIN');const session=await client.query(`SELECT id,name,service_type,started_at,status FROM sessions WHERE id=$1 AND organization_id=$2 LIMIT 1`,[sessionId,orgId]);if(!session.rows.length)throw new Error('Session does not belong to organization');sessionRow=session.rows[0];const attendance=await client.query(`SELECT ar.id,ar.people_id,ar.attendance_date FROM attendance_records ar JOIN people p ON p.id=ar.people_id AND p.organization_id=ar.organization_id WHERE ar.session_id=$1 AND ar.organization_id=$2 AND ar.confirmed=true AND ar.present=true AND COALESCE(p.status,'active')<>'merged'`,[sessionId,orgId]);for(const row of attendance.rows){const inserted=await client.query(`INSERT INTO participation_records(organization_id,person_id,session_id,participation_type,value,occurred_at) VALUES($1,$2,$3,'attendance',$4,$5) ON CONFLICT(organization_id,person_id,session_id,participation_type) WHERE participation_type='attendance' DO NOTHING RETURNING id`,[orgId,row.people_id,sessionId,JSON.stringify({present:true,source:'attendance_confirmation'}),row.attendance_date]);records.push({participationId:inserted.rows[0]?.id||null,personId:row.people_id});}await client.query('COMMIT');}catch(error){try{await client.query('ROLLBACK')}catch{}throw error}finally{client.release()}
 const personIds=[...new Set(records.map(x=>x.personId))],created=records.filter(x=>x.participationId),failures=[];
 for(const personId of personIds)try{await updateEngagementMetricsForPerson(personId,orgId)}catch(error){failures.push(`engagement:${personId}:${error.message}`);console.error('[ARIA] engagement:',error.message)}
 try{await computeRelationshipScore(orgId)}catch(error){failures.push(`relationship:${error.message}`);console.error('[ARIA] relationship:',error.message)}
 for(const row of records)try{const event=await emitAriaEvent({organizationId:orgId,personId:row.personId,type:'PARTICIPATION_CONFIRMED',source:'attendance',metadata:{session_id:sessionId,participation_id:row.participationId},eventKey:`participation:${row.participationId}:confirmed`});if(event)await processAriaEvent(event)}const returnAction=await handleReturnAfterAbsence({sessionId,orgId,personId:row.personId});if(returnAction){}catch(error){failures.push(`event:${row.personId}:${error.message}`);console.error('[ARIA] participation event:',error.message)}
 let immediateActions=0,absenceObservations=0;
 try{const absent=await pool.query(`SELECT p.id,p.first_name,p.last_name,p.display_name,p.phone,p.email FROM people p WHERE p.organization_id=$1 AND p.status='active' AND NOT EXISTS(SELECT 1 FROM attendance_records ar WHERE ar.organization_id=$1 AND ar.people_id=p.id AND ar.session_id=$2 AND ar.present=true AND ar.confirmed=true)
  AND NOT EXISTS(SELECT 1 FROM aria_attendance_contexts ac WHERE ac.organization_id=$1 AND ac.person_id=p.id AND ac.session_id=$2) AND NOT EXISTS(SELECT 1 FROM aria_care_contexts c WHERE c.organization_id=$1 AND c.person_id=p.id AND c.kind IN('travel','temporary_unavailable','not_attending') AND(c.ends_on IS NULL OR c.ends_on>CURRENT_DATE)) AND NOT EXISTS(SELECT 1 FROM aria_care_contexts c WHERE c.organization_id=$1 AND c.person_id=p.id AND c.kind='preferred_service' AND c.ends_on IS NULL AND c.service_type IS NOT NULL AND c.service_type<>COALESCE(NULLIF($3,''),'weekday:'||EXTRACT(ISODOW FROM $4::timestamptz)::int)) ORDER BY p.first_name,p.last_name`,[orgId,sessionId,sessionRow.service_type||'',sessionRow.started_at]);for(const person of absent.rows){const sourceEventId=`attendance:${sessionId}:absence:${person.id}`;const observationId=await createObservation({organizationId:orgId,personId:person.id,type:'UNUSUAL_ABSENCE',confidence:1,severity:'low',urgency:'low',evidence:{sources:['attendance'],facts:['Person was not recorded as present in this completed session'],inference:'This is an immediate absence signal, not a claim about an established attendance pattern.',session_id:sessionId,session_name:sessionRow.name||null,service_type:sessionRow.service_type||null},sourceEventId});absenceObservations++;await updatePersonState(person.id,orgId);const action=await planActionFromObservation({organizationId:orgId,personId:person.id,observationId,actionType:'SEND_MESSAGE',priority:'low',actionMetadata:{kind:'first_session_check_in',reason:'ARIA noticed this person was not observed in the completed session.',requires_human_approval:true,draft_required:true,channel:'whatsapp',first_session:true,pattern_claim:false},actionKey:`briefing:first_session_absence:${sessionId}:${person.id}`});if(action)immediateActions++;}}catch(error){failures.push(`absence:${error.message}`);console.error('[ARIA] immediate absence response:',error.message)}
 if(failures.length)throw new Error(`ARIA processing incomplete: ${failures.slice(0,5).join('; ')}`);
 return{session_id:sessionId,processed:personIds.length,events:created.length,absence_observations:absenceObservations,immediate_actions:immediateActions};
}
