// lib/aria/recommendationEngine.js
import pool from'../db';
const ORDER={critical:4,high:3,medium:2,low:1};const normalize=p=>ORDER[p]?p:'medium';
export async function planActionFromObservation({organizationId,personId=null,observationId=null,actionType,priority='medium',actionMetadata={},actionKey=null},client=null){if(!organizationId||!actionType)throw new Error('organizationId and actionType are required');const key=actionKey||[organizationId,personId||'global',actionType,observationId||'none'].join(':');const db=client||pool;const r=await db.query(`INSERT INTO aria_actions(organization_id,person_id,observation_id,type,status,priority,action_metadata,action_key,proposed_at) VALUES($1,$2,$3,$4,'proposed',$5,$6,$7,NOW()) ON CONFLICT(organization_id,action_key) DO NOTHING RETURNING *`,[organizationId,personId,observationId,actionType,normalize(priority),actionMetadata,key]);return r.rows[0]||null;}

export async function prepareAndApproveAction({organizationId,personId,actionType='SEND_MESSAGE',priority='medium',actionMetadata={},actorId}){
 if(!organizationId||!personId||!actorId)throw new Error('organizationId, personId and actorId are required');
 const client=await pool.connect();
 try{
  await client.query('BEGIN');
  const existing=await client.query(`SELECT * FROM aria_actions WHERE organization_id=$1 AND person_id=$2 AND type=$3 AND action_key=$4 AND status IN('proposed','approved') ORDER BY CASE WHEN status='approved' THEN 0 ELSE 1 END,created_at DESC LIMIT 1 FOR UPDATE`,[organizationId,personId,actionType,`talk:${organizationId}:${personId}:${actionType}`]);
  let action=existing.rows[0]||null;
  if(!action){
   action=await planActionFromObservation({organizationId,personId,actionType,priority,actionMetadata:{...actionMetadata,requires_human_approval:true},actionKey:`talk:${organizationId}:${personId}:${actionType}`},client);
  }
  if(!action)throw new Error('The next action could not be prepared.');
  if(action.status==='approved'){await client.query('COMMIT');return action;}
  const approved=await client.query(`UPDATE aria_actions SET status='approved',approved_by=$3,approved_at=NOW(),updated_at=NOW(),action_metadata=COALESCE(action_metadata,'{}'::jsonb)||$4::jsonb WHERE id=$1 AND organization_id=$2 AND status='proposed' RETURNING *`,[action.id,organizationId,actorId,JSON.stringify(actionMetadata||{})]);
  if(!approved.rows.length)throw new Error('Action could not be approved.');
  await client.query('COMMIT');return approved.rows[0];
 }catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
}

export async function approveAction(actionId,organizationId,userId){if(!actionId||!organizationId||!userId)throw new Error('actionId, organizationId and userId are required');const r=await pool.query(`UPDATE aria_actions a SET status='approved',approved_by=$3,approved_at=NOW(),updated_at=NOW() FROM users u WHERE a.id=$1 AND a.organization_id=$2 AND a.status='proposed' AND a.approved_by IS NULL AND u.id=$3 AND u.organization_id=$2 AND u.active=true RETURNING a.*`,[actionId,organizationId,userId]);return r.rows[0]||null;}
export async function rejectAction(actionId,organizationId,reason=null){if(!actionId||!organizationId)throw new Error('actionId and organizationId required');const r=await pool.query(`UPDATE aria_actions SET status='cancelled',failure_reason=$1,updated_at=NOW() WHERE id=$2 AND organization_id=$3 AND status IN('proposed','approved') RETURNING *`,[reason,actionId,organizationId]);return r.rows[0]||null;}
export async function executeAction(actionId,organizationId){if(!actionId||!organizationId)throw new Error('actionId and organizationId required');const r=await pool.query(`SELECT * FROM aria_actions WHERE id=$1 AND organization_id=$2 LIMIT 1`,[actionId,organizationId]);if(!r.rows.length)throw new Error('Action not found');const action=r.rows[0];if(action.status!=='approved')throw new Error(`Action is not approved: ${action.status}`);if(action.expires_at&&new Date(action.expires_at)<=new Date())throw new Error('Action has expired');if(action.type==='SEND_MESSAGE')throw new Error('SEND_MESSAGE requires a confirmed external send; it cannot be marked executed by the manual WhatsApp flow.');const result=await pool.query(`UPDATE aria_actions SET status='executed',executed_at=NOW(),outcome=$1,updated_at=NOW() WHERE id=$2 AND organization_id=$3 AND status='approved' RETURNING *`,[{success:true},actionId,organizationId]);return result.rows[0]||null;}
export async function getPendingActions(orgId,limit=20){if(!orgId)throw new Error('orgId required');const n=Math.min(Math.max(Number(limit)||20,1),100);const r=await pool.query(`SELECT a.*,p.first_name,p.last_name,p.display_name,p.phone,p.email,o.type observation_type,o.severity,o.urgency,o.attention_score,o.evidence FROM aria_actions a LEFT JOIN people p ON p.id=a.person_id AND p.organization_id=a.organization_id LEFT JOIN aria_observations o ON o.id=a.observation_id AND o.organization_id=a.organization_id WHERE a.organization_id=$1 AND a.status IN('proposed','approved') AND(a.expires_at IS NULL OR a.expires_at>NOW()) ORDER BY CASE a.priority WHEN'critical'then 4 WHEN'high'then 3 WHEN'medium'then 2 ELSE 1 END DESC,a.proposed_at ASC LIMIT $2`,[orgId,n]);return r.rows;}
export async function getActionsForPerson(personId,orgId,limit=20){const n=Math.min(Math.max(Number(limit)||20,1),100);const r=await pool.query(`SELECT * FROM aria_actions WHERE person_id=$1 AND organization_id=$2 ORDER BY created_at DESC LIMIT $3`,[personId,orgId,n]);return r.rows;}
export async function generateActionsFromObservations(orgId){if(!orgId)throw new Error('orgId required');const r=await pool.query(`SELECT id,person_id,type,attention_score,severity,urgency,evidence FROM aria_observations WHERE organization_id=$1 AND status='active' AND attention_score>60 ORDER BY attention_score DESC,detected_at ASC`,[orgId]);const created=[];for(const o of r.rows){const action=await planActionFromObservation({organizationId:orgId,personId:o.person_id,observationId:o.id,actionType:'SEND_MESSAGE',priority:o.severity==='critical'?'critical':o.severity==='high'?'high':'medium',actionMetadata:{kind:'care',reason:'ARIA identified a meaningful care opportunity.',requires_human_approval:true,draft_required:true,channel:'whatsapp'}});if(action)created.push(action);}return created;}
