// components/AriaProcessingStatus.js
const ATTENDANCE_STEPS=[['persist','Saving the attendance','Your marks are safely stored.'],['return_signals','Checking return patterns','ARIA is comparing this session with recent participation.'],['absence_signals','Checking absence signals','ARIA is separating context from assumption.'],['engagement','Reading engagement','ARIA is updating participation signals.'],['relationship','Refreshing relationships','ARIA is updating relationship context.'],['people_intelligence','Updating people intelligence','ARIA is refreshing what changed for people.'],['person_state','Settling Living Truth','ARIA is deciding what is clear and what still needs evidence.'],['complete','Complete','The session is fully understood.']];
const SCAN_STEPS=[['preparing_image','Preparing the image','Getting the register ready.'],['reading_page','Reading the register','Reading names, numbers, and row structure.'],['auditing_rows','Checking extracted rows','Testing row and phone relationships.'],['validating','Validating the reading','Rejecting unsafe interpretations.'],['matching_community','Reconciling identities','Comparing against people already remembered.'],['building_memory','Remembering people','Saving only identities ARIA can safely resolve.'],['complete','Complete','The scan is finished.']];
const normalize=s=>String(s||'').toLowerCase();
export function processingSteps(kind='attendance'){return kind==='scan'?SCAN_STEPS:ATTENDANCE_STEPS}
export default function AriaProcessingStatus({kind='attendance',status='processing',stage='',progress=0,processed=0,total=0,error='',compact=false,onClick}){
 const steps=processingSteps(kind),current=normalize(stage)||normalize(status),idx=Math.max(0,steps.findIndex(x=>x[0]===current)),state=normalize(status);
 const done=state==='complete'||current==='complete',needs=state==='needs_attention'||state==='failed',pct=Math.max(0,Math.min(100,Number(progress)||0)),active=steps[idx]||steps[0];
 const title=needs?(state==='failed'?'ARIA stopped safely':'ARIA needs your attention'):done?'ARIA is done':kind==='scan'?'ARIA is thinking through the register':'ARIA is thinking through the session';
 return <div className={'ariaProcess '+(compact?'compact ':'')+(onClick?'clickable':'')} role={onClick?'button':undefined} tabIndex={onClick?0:-1} onClick={onClick} onKeyDown={e=>{if(onClick&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onClick()}}} aria-live="polite">
  <div className="ariaProcessTop"><span className={'ariaProcessOrb '+(needs?'attention ':done?'done':'')}><i/></span><span className="ariaProcessCopy"><strong>{title}</strong><small>{done?'You can continue normally.':needs?(error||active[2]):active[2]}</small></span><b className="ariaProcessPercent">{done?100:pct}%</b></div>
  {!compact&&<div className="ariaProcessSteps">{steps.map((x,i)=>{const isDone=done||i<idx,isCurrent=!done&&i===idx;return <div className={'ariaProcessStep '+(isDone?'isDone ':'')+(isCurrent?'isCurrent':'')} key={x[0]}><span>{isDone?'✓':isCurrent?'•':''}</span><div><b>{x[1]}</b>{isCurrent&&<small>{x[2]}</small>}</div></div>})}</div>}
  <div className="ariaProcessTrack"><i style={{width:(done?100:pct)+'%'}}/></div>
  {!compact&&processed>0&&total>0?<div className="ariaProcessMeta">{processed.toLocaleString()} of {total.toLocaleString()} people understood</div>:null}
  <style jsx>{'.ariaProcess{width:100%;box-sizing:border-box;text-align:left;border:1px solid rgba(143,175,214,.13);border-radius:16px;padding:11px 12px;background:linear-gradient(145deg,rgba(143,175,214,.06),rgba(255,255,255,.025));color:#F5F7FA}.ariaProcess.clickable{cursor:pointer}.ariaProcess.clickable:focus-visible{outline:2px solid rgba(232,212,154,.65);outline-offset:2px}.ariaProcessTop{display:flex;align-items:center;gap:9px}.ariaProcessOrb{width:28px;height:28px;display:grid;place-items:center;border-radius:50%;flex:0 0 auto;background:radial-gradient(circle,rgba(143,175,214,.28),rgba(143,175,214,.07) 56%,transparent 72%);border:1px solid rgba(143,175,214,.18)}.ariaProcessOrb i{width:6px;height:6px;border-radius:50%;background:#8FAFD6;box-shadow:0 0 10px rgba(143,175,214,.72);animation:ariaProcessBreathe 1.8s ease-in-out infinite}.ariaProcessOrb.done{background:radial-gradient(circle,rgba(127,191,154,.22),transparent 72%);border-color:rgba(127,191,154,.24)}.ariaProcessOrb.done i{background:#7FBF9A;box-shadow:0 0 10px rgba(127,191,154,.5);animation:none}.ariaProcessOrb.attention{background:radial-gradient(circle,rgba(214,184,106,.24),transparent 72%);border-color:rgba(214,184,106,.24)}.ariaProcessOrb.attention i{background:#D6B86A;box-shadow:0 0 10px rgba(214,184,106,.55);animation:none}.ariaProcessCopy{min-width:0;flex:1;display:grid;gap:2px}.ariaProcessCopy strong{font-size:12px}.ariaProcessCopy small{font-size:10px;line-height:1.35;color:rgba(245,247,250,.42)}.ariaProcessPercent{font-size:10px;color:rgba(245,247,250,.5)}.ariaProcessSteps{display:grid;gap:5px;margin:10px 0 7px;padding-left:37px}.ariaProcessStep{display:flex;gap:8px;align-items:flex-start;color:rgba(245,247,250,.25)}.ariaProcessStep>span{width:14px;text-align:center;font-size:10px}.ariaProcessStep>div{display:grid;gap:2px}.ariaProcessStep b{font-size:9.5px;font-weight:550}.ariaProcessStep small{font-size:9.5px;line-height:1.35;color:rgba(245,247,250,.36)}.ariaProcessStep.isDone{color:rgba(127,191,154,.8)}.ariaProcessStep.isCurrent{color:#F5F7FA}.ariaProcessTrack{height:4px;border-radius:99px;background:rgba(255,255,255,.07);overflow:hidden;margin-top:6px}.ariaProcessTrack i{display:block;height:100%;border-radius:99px;background:linear-gradient(90deg,rgba(143,175,214,.3),rgba(214,184,106,.82));transition:width .45s ease}.ariaProcessMeta{margin-top:7px;font-size:9px;color:rgba(245,247,250,.28)}.ariaProcess.compact{padding:9px 10px;border-radius:14px}.ariaProcess.compact .ariaProcessOrb{width:24px;height:24px}.ariaProcess.compact .ariaProcessCopy strong{font-size:11px}.ariaProcess.compact .ariaProcessCopy small{font-size:9.5px}.ariaProcess.compact .ariaProcessPercent{font-size:9px}@keyframes ariaProcessBreathe{0%,100%{transform:scale(.72);opacity:.45}50%{transform:scale(1.08);opacity:1}}@media(prefers-reduced-motion:reduce){.ariaProcessOrb i{animation:none}}@media(prefers-reduced-transparency:reduce){.ariaProcess{background:#101A31}}'}
  </style>
 </div>
}
