// components/ScanModal.js
import{useState,useRef,useEffect,useCallback}from'react'
import{createPortal}from'react-dom'
import{useRouter}from'next/router'
import{supabase}from'../lib/supabaseClient'
import{getScanState,setScanState,clearScanState}from'../lib/scanStore'
import{useOnboarding}from'./OnboardingProvider'
const DEFAULT_PROGRAM='GIBEON',MAX_BYTES=3500000,MAX_DIM=2200,POLL=1200
const nameOf=v=>String(v||'').trim().replace(/\s+/g,' ').split(' ').map(x=>x?x[0].toUpperCase()+x.slice(1).toLowerCase():'').join(' ')
const progressText=(p,s)=>({queued:'ARIA is preparing the register…',enhancing:'ARIA is enhancing the image…',layout_analysis:'ARIA is reading the register structure…',reading_handwriting:'ARIA is reading the handwriting…',verifying_rows:'ARIA is checking the physical rows…',validating:'ARIA is validating the extracted records…',matching_community:'ARIA is comparing the register with the community…',building_memory:'ARIA is preparing the records for review…',retrying:'ARIA is retrying safely…'})[p]||(s==='pending'?'ARIA is preparing your scan…':'ARIA is working through the register…')
export default function ScanModal({isOpen,onClose}){
 const router=useRouter(),onboarding=useOnboarding(),cameraInput=useRef(null),uploadInput=useRef(null),poll=useRef(null),job=useRef(null)
 const[mounted,setMounted]=useState(false),[program,setProgram]=useState(DEFAULT_PROGRAM),[state,setState]=useState(getScanState()),[message,setMessage]=useState(''),[elapsed,setElapsed]=useState(0),[doneAt,setDoneAt]=useState(null),[celebrate,setCelebrate]=useState(false)
 useEffect(()=>{setMounted(true);return()=>setMounted(false)},[])
 const sync=useCallback(v=>{setScanState(v);setState(getScanState())},[])
 const stopPoll=useCallback(()=>{if(poll.current){clearInterval(poll.current);poll.current=null}job.current=null},[])
 const finish=useCallback(async()=>{if(!onboarding?.enabled||onboarding.isExperienced('scan'))return;try{const{data:{session}}=await supabase.auth.getSession();if(!session)return;const r=await fetch('/api/onboarding',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action:'experience_completed',experience:'scan'})});if(r.ok)onboarding.completeExperience('scan')}catch{}},[onboarding])
 const watch=useCallback(id=>{if(!id||job.current===id)return;stopPoll();job.current=id;const run=async()=>{try{const{data:{session}}=await supabase.auth.getSession();if(!session)return;const r=await fetch(`/api/scan/status?job_id=${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)return;setElapsed(Number(d.elapsed_seconds)||0);if(['pending','processing','retrying'].includes(d.status)){const m=d.message||progressText(d.progress,d.status);setMessage(m);sync({stage:'processing',jobId:id,progress:d.progress||'queued',message:m});return}if(d.status==='complete'){stopPoll();const result=d.result||{},people=Array.isArray(result.people)?result.people:[],review=Array.isArray(result.needs_review)?result.needs_review:Array.isArray(result.review)?result.review:[],summary={total:Number(result.total_extracted??result.total_valid??people.length??0),newVisitors:Number(result.new_members||0),returning:Number(result.updated||0),duplicates:Array.isArray(result.duplicates)?result.duplicates.length:Number(result.duplicates||0),needsReview:Number(result.needs_review_count??review.length??0)},normalized=people.map(x=>({...x,name:nameOf(x.name)}));sync({stage:'complete',jobId:id,summary,results:{...result,people:normalized,needs_review:review},revealedPeople:normalized,ariaMessages:Array.isArray(result.aria_messages)?result.aria_messages:[]});setDoneAt(new Date().toLocaleString());setCelebrate(true);setTimeout(()=>setCelebrate(false),750);finish();return}if(d.status==='failed'){stopPoll();const m=d.message||'ARIA could not complete this scan.';setMessage(m);sync({stage:'error',jobId:id,message:m})}}catch(e){console.error('[SCAN] poll',e)}};run();poll.current=setInterval(run,POLL)},[finish,stopPoll,sync])
 useEffect(()=>{if(!isOpen)return;const s=getScanState();setState(s);if(s.stage==='processing'&&s.jobId){setMessage(s.message||'ARIA is continuing your scan…');watch(s.jobId)}return()=>stopPoll()},[isOpen,watch,stopPoll])
 useEffect(()=>{if(!isOpen||!mounted)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[isOpen,mounted])
 const prepare=useCallback(file=>new Promise((resolve,reject)=>{if(!file)return reject(Error('No image selected.'));if(!file.type?.startsWith('image/'))return reject(Error('Please choose a photo or image of the register.'));const u=URL.createObjectURL(file),im=new Image();im.onload=async()=>{try{const scale=Math.min(1,MAX_DIM/Math.max(im.naturalWidth,im.naturalHeight)),w=Math.max(1,Math.round(im.naturalWidth*scale)),h=Math.max(1,Math.round(im.naturalHeight*scale)),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{alpha:false});if(!x)throw Error('Image processing is unavailable on this device.');x.drawImage(im,0,0,w,h);let b=await new Promise(r=>c.toBlob(r,'image/jpeg',.9));if(!b)throw Error('Could not prepare the image.');if(b.size>MAX_BYTES)b=await new Promise(r=>c.toBlob(r,'image/jpeg',.76));if(!b||b.size>MAX_BYTES)throw Error('This image is too large. Please retake the photo from a little farther away.');const fr=new FileReader();fr.onload=()=>{URL.revokeObjectURL(u);resolve(String(fr.result||'').split(',')[1])};fr.onerror=()=>reject(Error('Could not read the prepared image.'));fr.readAsDataURL(b)}catch(e){URL.revokeObjectURL(u);reject(e)}};im.onerror=()=>{URL.revokeObjectURL(u);reject(Error('Failed to load the selected image.'))};im.src=u}),[])
 const send=useCallback(async file=>{if(!file||state.stage==='processing')return;const n=nameOf(program)||DEFAULT_PROGRAM;sync({stage:'processing',progress:'enhancing',message:'ARIA is preparing the image…'});setMessage('ARIA is preparing the image…');setElapsed(0);try{const image_base64=await prepare(file),{data:{session}}=await supabase.auth.getSession();if(!session)throw Error('You must be logged in to scan.');const r=await fetch('/api/scan/start',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({image_base64,program_name:n})}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'ARIA could not start the scan.');if(!d.job_id)throw Error('ARIA did not return a scan job.');sync({stage:'processing',jobId:d.job_id,progress:d.progress||'queued',message:d.message||'ARIA is preparing to read the register…'});setMessage(d.message||'ARIA is preparing to read the register…');watch(d.job_id)}catch(e){stopPoll();setMessage(e.message||'Failed to start scan.');sync({stage:'error',message:e.message||'Failed to start scan.'})}},[prepare,program,state.stage,stopPoll,sync,watch])
 const inputChange=useCallback(e=>{const f=e.target.files?.[0];e.target.value='';if(f)send(f)},[send])
 if(!isOpen||!mounted)return null
 const close=()=>{if(state.stage==='processing')return;stopPoll();clearScanState();setState(getScanState());setMessage('');onClose?.()},reset=()=>{stopPoll();clearScanState();setState(getScanState());setMessage('');setElapsed(0);setDoneAt(null);setCelebrate(false)}
 const{stage,summary,message:storedMessage}=state,result=state.results||{},count=summary?.total??result.total_extracted??result.total_valid??result.people?.length??0,reviewCount=summary?.needsReview??result.needs_review?.length??0,phase={queued:['Preparing',8],enhancing:['Preparing image',18],layout_analysis:['Reading structure',32],reading_handwriting:['Reading handwriting',52],verifying_rows:['Checking rows',68],validating:['Validating extraction',80],matching_community:['Comparing community',90],building_memory:['Preparing review',97],retrying:['Retrying safely',68]}[state.progress]||['Preparing',8]
 const content=<div style={s.overlay} onMouseDown={e=>{if(e.target===e.currentTarget&&stage!=='processing')close()}}><div style={s.modal} role="dialog" aria-modal="true" aria-label="ARIA Scan"><button style={s.close} onClick={close} disabled={stage==='processing'}>×</button><div style={s.inner}>
  {stage==='idle'&&<><div style={s.eyebrow}>ARIA · SCAN</div><h2 style={s.title}>Remember people.</h2><p style={s.sub}>ARIA reads the register intelligently and sends uncertain records to Review Center instead of guessing.</p><input value={program} onChange={e=>setProgram(e.target.value)} placeholder="Program name" style={s.input}/><label style={s.primary}>Take photo<input ref={cameraInput} type="file" accept="image/*" capture="environment" hidden onChange={inputChange}/></label><button style={s.secondary} onClick={()=>uploadInput.current?.click()}>Upload image</button><input ref={uploadInput} type="file" accept="image/*,.png,.jpg,.jpeg,.webp" hidden onChange={inputChange}/><div style={s.hint}>Take photo uses your phone camera. Upload image opens your phone's normal file/gallery chooser.</div></>}
  {stage==='processing'&&<div style={s.center}><div style={s.pulse}>✦</div><strong>{message||phase[0]}</strong><div style={s.track}><i style={{width:`${phase[1]}%`}}/></div><small>{elapsed}s · ARIA is extracting first, deciding later</small></div>}
  {stage==='complete'&&<div style={s.center}><div style={s.success}>✓ Register remembered.</div><strong>{count} {Number(count)===1?'person':'people'} processed.</strong><span style={s.sub}>{reviewCount?`${reviewCount} ${reviewCount===1?'row was':'rows were'} preserved in Review Center rather than guessed.`:'ARIA completed the extraction without needing additional review.'}</span><button style={s.secondary} onClick={reset}>Scan another</button>{reviewCount>0&&<button style={s.secondary} onClick={()=>router.push('/review')}>Review {reviewCount} records</button>}<button style={s.secondary} onClick={()=>router.push('/people')}>View community</button>{doneAt&&<small>{doneAt}</small>}</div>}
  {stage==='error'&&<div style={s.center}><div style={s.error}>Scan not completed.</div><span style={s.sub}>{storedMessage||'ARIA stopped safely.'}</span><button style={s.secondary} onClick={reset}>Try again</button></div>}
 </div></div></div>
 return createPortal(content,document.body)
}
const s={overlay:{position:'fixed',inset:0,zIndex:100000,display:'grid',placeItems:'center',padding:14,background:'rgba(2,6,16,.68)',backdropFilter:'blur(16px)',WebkitBackdropFilter:'blur(16px)'},modal:{position:'relative',width:'min(580px,calc(100vw - 28px))',height:'75vh',maxHeight:'75vh',overflowY:'auto',boxSizing:'border-box',borderRadius:30,background:'linear-gradient(145deg,rgba(16,27,55,.98),rgba(7,14,32,.98))',border:'1px solid rgba(255,255,255,.11)',boxShadow:'0 30px 100px rgba(0,0,0,.55)',color:'#fff'},close:{position:'absolute',top:14,right:14,width:38,height:38,borderRadius:'50%',border:'1px solid rgba(255,255,255,.1)',background:'rgba(255,255,255,.06)',color:'rgba(255,255,255,.8)',fontSize:25,lineHeight:1,cursor:'pointer',zIndex:5},inner:{minHeight:'100%',maxWidth:500,margin:'0 auto',padding:'48px 24px 34px',boxSizing:'border-box',display:'flex',flexDirection:'column',justifyContent:'center',textAlign:'center'},eyebrow:{fontSize:10,letterSpacing:2.5,color:'rgba(255,255,255,.35)',marginBottom:10},title:{fontSize:'clamp(27px,7vw,38px)',lineHeight:1.05,letterSpacing:-1.2,margin:'0 0 12px'},sub:{margin:'0 auto 18px',maxWidth:440,color:'rgba(255,255,255,.45)',lineHeight:1.6,fontSize:14},input:{width:'100%',boxSizing:'border-box',padding:'14px 16px',borderRadius:16,border:'1px solid rgba(255,255,255,.12)',background:'rgba(255,255,255,.06)',color:'#fff',outline:'none',fontSize:16,marginBottom:12},primary:{display:'block',width:'100%',boxSizing:'border-box',padding:'15px 18px',borderRadius:16,border:'1px solid rgba(212,175,55,.4)',background:'linear-gradient(135deg,rgba(212,175,55,.22),rgba(255,255,255,.08))',color:'#fff',fontWeight:700,cursor:'pointer',marginBottom:10},secondary:{display:'block',width:'100%',boxSizing:'border-box',padding:'15px 18px',borderRadius:16,border:'1px solid rgba(255,255,255,.12)',background:'rgba(255,255,255,.06)',color:'#fff',fontWeight:600,cursor:'pointer',marginBottom:10},hint:{fontSize:12,color:'rgba(255,255,255,.32)',lineHeight:1.5,marginTop:8},center:{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',gap:14},pulse:{fontSize:34,animation:'ariaPulse 1.4s ease-in-out infinite'},track:{width:'min(100%,360px)',height:7,borderRadius:99,background:'rgba(255,255,255,.1)',overflow:'hidden'},progress:{height:'100%',borderRadius:99,background:'#d4af37'},success:{fontSize:18,fontWeight:700},error:{fontSize:18,fontWeight:700,color:'#ffb4b4'}}