// components/ScanMediaMenu.js
import{useEffect,useState}from'react'
export default function ScanMediaMenu(){
 const[open,setOpen]=useState(false)
 useEffect(()=>{
  const isTrigger=el=>{const t=(el?.textContent||'').replace(/\s+/g,' ').trim().toLowerCase();return t==='upload'||t==='open camera'||t==='gallery'||t.includes('upload image')}
  const onClick=e=>{const b=e.target?.closest?.('button');if(!b||b.dataset.nyeoMediaAction||!isTrigger(b))return;if(b.dataset.nyeoMediaBypass)return;e.preventDefault();e.stopPropagation();setOpen(true)}
  document.addEventListener('click',onClick,true);return()=>document.removeEventListener('click',onClick,true)
 },[])
 const original=(names)=>{const buttons=[...document.querySelectorAll('button')];const b=buttons.find(x=>{const t=(x.textContent||'').replace(/\s+/g,' ').trim().toLowerCase();return names.some(n=>t===n)||names.some(n=>t.includes(n))});if(b){b.dataset.nyeoMediaBypass='1';b.click();delete b.dataset.nyeoMediaBypass}}
 const files=()=>{const i=[...document.querySelectorAll('input[type="file"]')].find(x=>!x.disabled);if(i){i.click();return}const i2=document.createElement('input');i2.type='file';i2.accept='image/*';i2.style.display='none';document.body.appendChild(i2);i2.click();i2.remove()}
 const camera=()=>{setOpen(false);original(['open camera','camera'])}
 const downloads=()=>{setOpen(false);files()}
 const quickShare=async()=>{setOpen(false);try{if(navigator.share)await navigator.share({title:'NYEOCARE',text:'Share a file with NYEOCARE'});else files()}catch(e){if(e?.name!=='AbortError')files()}}
 if(!open)return null
 return <div style={s.backdrop} onClick={()=>setOpen(false)}><div style={s.sheet} onClick={e=>e.stopPropagation()}><div style={s.handle}/><div style={s.title}>Add to NYEOCARE</div><div style={s.sub}>Choose where the scan comes from</div><div style={s.options}><button data-nyeo-media-action style={s.option} onClick={camera}><span style={s.icon}>⌾</span><span><b>Camera</b><small>Take a new photo</small></span></button><button data-nyeo-media-action style={s.option} onClick={downloads}><span style={s.icon}>↓</span><span><b>Downloads</b><small>Choose from your device</small></span></button><button data-nyeo-media-action style={s.option} onClick={quickShare}><span style={s.icon}>↗</span><span><b>Quick Share</b><small>Share from another app</small></span></button></div></div></div>
}
const s={backdrop:{position:'fixed',inset:0,zIndex:99999,display:'flex',alignItems:'flex-end',justifyContent:'center',background:'rgba(2,7,17,.28)',backdropFilter:'blur(5px)',WebkitBackdropFilter:'blur(5px)'},sheet:{width:'min(430px,100%)',padding:'8px 14px calc(14px + env(safe-area-inset-bottom))',borderRadius:'26px 26px 0 0',background:'rgba(9,18,38,.97)',border:'1px solid rgba(255,255,255,.09)',boxShadow:'0 -18px 60px rgba(0,0,0,.42)',animation:'nyeoMediaSheet .22s cubic-bezier(.2,.8,.2,1)'},handle:{width:38,height:4,borderRadius:99,background:'rgba(255,255,255,.2)',margin:'0 auto 13px'},title:{fontSize:17,fontWeight:650,color:'#fff',padding:'0 4px'},sub:{fontSize:11,color:'rgba(255,255,255,.42)',padding:'3px 4px 11px'},options:{display:'grid',gap:7},option:{width:'100%',minHeight:57,border:'1px solid rgba(255,255,255,.065)',borderRadius:16,background:'rgba(255,255,255,.045)',color:'#fff',display:'flex',alignItems:'center',gap:13,padding:'9px 13px',textAlign:'left',cursor:'pointer'},icon:{width:34,height:34,borderRadius:12,display:'grid',placeItems:'center',background:'rgba(143,175,214,.1)',color:'#D6B86A',fontSize:20,flexShrink:0},small:{display:'block',fontSize:10,color:'rgba(255,255,255,.38)',marginTop:2,fontWeight:400}}
