// lib/aiObserver.js
import{calculateEstimatedCost}from'./costCalculator';
import crypto from'crypto';
let poolPromise=null;
async function getPool(){if(poolPromise)return poolPromise;poolPromise=import('./db').then(m=>m.default);return poolPromise}
export async function logAIUsage({organization_id,job_id=null,request_id=null,model_key,provider,model,purpose,prompt_version='v1',attempt=1,input_tokens=null,output_tokens=null,reasoning_tokens=null,latency_ms=null,finish_reason=null,http_status=null,success=false,retry_reason=null,rate_limit_remaining_tokens=null,rate_limit_remaining_requests=null,rate_limit_reset_tokens=null,rate_limit_reset_requests=null,retry_after=null}){
 const requestId=request_id||crypto.randomUUID(),input=typeof input_tokens==='number'&&Number.isFinite(input_tokens)&&input_tokens>=0?Math.floor(input_tokens):null,output=typeof output_tokens==='number'&&Number.isFinite(output_tokens)&&output_tokens>=0?Math.floor(output_tokens):null,reasoning=typeof reasoning_tokens==='number'&&Number.isFinite(reasoning_tokens)&&reasoning_tokens>=0?Math.floor(reasoning_tokens):null,total=input!==null&&output!==null?input+output:null;
 let inputCost=null,outputCost=null,totalCost=null;if(input!==null&&output!==null)try{const c=calculateEstimatedCost(model_key,input,output);inputCost=c.inputCost;outputCost=c.outputCost;totalCost=c.totalCost}catch(err){console.error('[AI Observer] Cost calculation:',err?.message||err)}
 const payload=[organization_id,job_id,requestId,provider,model,model_key,purpose,prompt_version,attempt,input,output,reasoning,total,latency_ms,finish_reason,http_status,Boolean(success),retry_reason,inputCost,outputCost,totalCost,rate_limit_remaining_tokens,rate_limit_remaining_requests,rate_limit_reset_tokens,rate_limit_reset_requests,retry_after];
 try{const pool=await getPool();const query=pool.query(`INSERT INTO ai_usage_events(organization_id,job_id,request_id,provider,model,model_key,purpose,prompt_version,attempt,input_tokens,output_tokens,reasoning_tokens,total_tokens,latency_ms,finish_reason,http_status,success,retry_reason,estimated_input_cost,estimated_output_cost,estimated_total_cost,rate_limit_remaining_tokens,rate_limit_remaining_requests,rate_limit_reset_tokens,rate_limit_reset_requests,retry_after)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26)`,payload);query.catch(err=>console.error('[AI Observer] Failed to log usage:',err?.message||err))}catch(err){console.error('[AI Observer] Telemetry unavailable:',err?.message||err)}return requestId;
}
export async function updateExtractionMetrics(requestId,extractionCount,validationCount,reviewCount){if(!requestId)return;try{const pool=await getPool();pool.query(`UPDATE ai_usage_events SET extraction_metrics=jsonb_build_object('extraction_count',$1,'validation_count',$2,'review_count',$3) WHERE request_id=$4`,[extractionCount,validationCount,reviewCount]).catch(err=>console.error('[AI Observer] Extraction metrics:',err?.message||err))}catch(err){console.error('[AI Observer] Metrics unavailable:',err?.message||err))}}
