// lib/aiProvider.js
import{getModelConfig}from'./modelRegistry';
import{logAIUsage}from'./aiObserver';
import crypto from'crypto';
const GROQ_API_KEY=process.env.GROQ_API_KEY;
const GROQ_URL='https://api.groq.com/openai/v1/chat/completions';
const MODEL_KEY=process.env.GROQ_VISION_MODEL_KEY||'groq-qwen3.8-27b';
const MODEL=getModelConfig(MODEL_KEY);
export const SCAN_PIPELINE_VERSION='v28-canonical-scan';
const MAX_PEOPLE_PER_PAGE=50;
const CONFIGURED_CEILING=Number(process.env.GROQ_SCAN_OUTPUT_CEILING||MODEL.max_completion_tokens||1000);
const PROVIDER_OUTPUT_CEILING=Math.min(1000,Number.isFinite(CONFIGURED_CEILING)&&CONFIGURED_CEILING>0?CONFIGURED_CEILING:1000);
const SAFE_OUTPUT_CEILING=PROVIDER_OUTPUT_CEILING;
const MIN_OUTPUT=700;
const DEFAULT_OUTPUT=Math.min(900,SAFE_OUTPUT_CEILING);
const RECOVERY_MAX=SAFE_OUTPUT_CEILING;
const MAX_RETRIES=2;
const TIMEOUT=90000;
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
function cleanName(value){return String(value||'').replace(/\s+/g,' ').trim()}
const TITLES={mr:'Mr',mrs:'Mrs',ms:'Ms',miss:'Miss',bro:'Bro',brother:'Brother',sis:'Sis',sister:'Sister',pastor:'Pastor',past:'Past',pst:'Pst',rev:'Rev',reverend:'Reverend',dr:'Dr',doctor:'Doctor',elder:'Elder',deacon:'Deacon',deaconess:'Deaconess',chief:'Chief',bishop:'Bishop',apostle:'Apostle',evangelist:'Evangelist',prophet:'Prophet',minister:'Minister',canon:'Canon',father:'Father',archbishop:'Archbishop'};
function capitalizeName(value){return cleanName(value).split(/\s+/).map(part=>part.replace(/[A-Za-zÀ-ÖØ-öø-ÿ]+/g,word=>TITLES[word.toLowerCase()]||word.charAt(0).toUpperCase()+word.slice(1).toLowerCase())).join(' ')}
function parseJSON(text){if(typeof text!=='string'||!text.trim())return null;const cleaned=text.replace(/<think>[\s\S]*?<\/think>/gi,'').replace(/```json/gi,'').replace(/```/g,'').trim();try{return JSON.parse(cleaned)}catch{}const match=cleaned.match(/\{[\s\S]*\}/);if(match)try{return JSON.parse(match[0])}catch{}return null}
function phoneValues(value){const phones=value?.p??value?.phones??value?.phone;if(Array.isArray(phones))return phones.map(v=>String(v??'').trim()).filter(Boolean).slice(0,2);if(phones==null)return[];const phone=String(phones).trim();return phone?[phone]:[]}
function personKey(value){const name=cleanName(value?.n??value?.name??'').toLowerCase(),phones=phoneValues(value).map(v=>String(v).replace(/[\s()-]/g,'')).filter(Boolean).sort(),row=Number.isFinite(Number(value?.r))?Number(value.r):null;return`${row==null?'':`r${row}|`}${name}|${phones.join(',')}`}
function compactPeople(parsed){const rows=Array.isArray(parsed?.people)?parsed.people:Array.isArray(parsed)?parsed:[],seen=new Set(),people=[];for(let i=0;i<rows.length;i++){const row=rows[i],rawName=cleanName(row?.n??row?.name??''),name=capitalizeName(rawName),phones=phoneValues(row),modelRow=Number.isInteger(Number(row?.r))&&Number(row.r)>=1&&Number(row.r)<=MAX_PEOPLE_PER_PAGE?Number(row.r):null,rowNumber=modelRow||i+1,person={name,raw_name:rawName,phone:phones[0]||null,phones,rawPhones:phones,confidence:0,name_confidence:0,phone_confidence:0,pair_confidence:0,row_number:rowNumber,model_row_number:modelRow};if(!person.name&&!person.phone)continue;const key=personKey({...row,r:rowNumber,n:name});if(seen.has(key))continue;seen.add(key);people.push(person);if(people.length>=MAX_PEOPLE_PER_PAGE)break}return people}
function schema(){return{type:'json_schema',json_schema:{name:'scan_people',strict:true,schema:{type:'object',properties:{people:{type:'array',items:{type:'object',properties:{r:{type:'integer',minimum:1,maximum:50},n:{type:'string'},p:{type:'array',items:{type:'string'},maxItems:2}},required:['r','n','p'],additionalProperties:false}}},required:['people'],additionalProperties:false}}}}
function responseFormat(){return MODEL.supports_structured_output?schema():{type:'json_object'}}
function primaryPrompt(){return`You are the vision data-entry specialist for NYEOCARE, a Nigerian church/organization records system. Read the ORIGINAL photographed handwritten register page as a human data-entry clerk would: understand the page layout first, then extract each real person row and the phone number(s) physically belonging to that same row. Return ONLY compact JSON: {"people":[{"r":1,"n":"Sis Sandra Isiche","p":["08039579788"]}]}.
EXTRACTION CONTRACT:
- Inspect the whole ORIGINAL page before producing output. Read top-to-bottom and treat each distinct non-empty person/register row as one record. Maximum 50.
- r is the physical row order observed on the page, starting at 1 for the first non-empty person row. Never invent extra rows. Never repeat a row.
- One physical person row = one JSON object. Never combine adjacent people and never split one person across two objects.
- Do not stop early. The last visible person is as important as the first.
- n is the COMPLETE visible person name/identifier for THAT row.
- p contains every phone visibly assigned to THAT SAME row, in the order visible. Support up to two genuine phones; never invent a third.
PHONE ACCURACY:
- Pair phones visually, not by sequence memory. First identify the horizontal row/line and its nearby fields, then read its digits.
- Never borrow a phone from the row above or below, even when the names look related.
- Read the ORIGINAL digits only. Never autocomplete, infer, repair or substitute a digit to make a number look valid.
- Preserve a visible leading 0 or +234 and keep internal digit order exactly as written.
- If a phone is partly unreadable, do not fabricate it. Omit only that unreadable phone from p rather than creating a false number.
- If two phone numbers are clearly connected to one person, return both.
NAME ACCURACY:
- Preserve meaningful prefixes/suffixes used by the church or organization as part of the displayed identity: Sis, Sister, Bro, Brother, Mr, Mrs, Miss, Ms, Pastor, Rev, Reverend, Dr, Doctor, Elder, Deacon, Deaconess, Chief, Bishop, Apostle, Evangelist, Prophet, Minister, Canon, Father, Archbishop and similar visible identifiers.
- Preserve the title exactly where it appears. Never strip it, move it, invent it, expand it, abbreviate it or replace it with another title.
- Examples: "Mr Egwame Oshiogwe Nicholas", "Sis Peace", "Eze", "Mr Dominion", "John Eze, Pastor".
- Name output should be normally capitalized, not ALL CAPS or all lowercase. Preserve meaningful hyphens/apostrophes.
- Use strong recognition knowledge of Nigerian, other African and English names. Interpret handwriting in context rather than treating each character as isolated OCR.
- Common handwritten confusions may include c/e, e/i, r/n, m/n, u/v, b/d, o/a, l/i, s/r and similar letter-shape errors. Resolve an obvious error only when the actual writing strongly supports the corrected real name.
- Prefer a plausible real Nigerian/African/English spelling when the handwriting is genuinely ambiguous, but NEVER replace a clearly written uncommon name merely because a familiar spelling is more common.
- Similar spellings such as Eze/Ezie, Tonia/Tonna, Nicholas/Nicolas, Chinedu/Chinendu are possible variants, not automatic corrections.
PAIRING + PAGE CONTROL:
- Keep names and phone numbers tied to their physical row. A correct phone attached to the wrong name is a failure.
- Ignore headers, totals, dates, notes, signatures and unrelated numbers.
- Do not output commentary, markdown, explanations or confidence prose.
FINAL SILENT CHECK BEFORE RETURNING JSON:
1. Re-scan the ORIGINAL page from the top and count the non-empty person rows.
2. Ensure every observed person row appears exactly once in the JSON.
3. Ensure r values are sequential in physical reading order.
4. Ensure no person is duplicated merely because handwriting was difficult.
5. For every row, look specifically at the phone field beside/within that row and verify the digits belong to that person.
6. Re-read every name for Nigerian/African/English spelling plausibility without overwriting clear handwriting.
7. Check the final row again so no person at the bottom is lost.`}
async function safeLog(data){try{return await logAIUsage(data)}catch{return null}}
function retryDelay(error,attempt){const header=Number(error?.retryAfter);if(Number.isFinite(header)&&header>0)return Math.min(header*1000+500,90000);const message=String(error?.message||''),seconds=message.match(/try again in\s+(\d+(?:\.\d+)?)s/i);if(seconds)return Math.min(Number(seconds[1])*1000+500,90000);return Math.min(1500*Math.pow(2,attempt-1),8000)}
function imageBytes(imageBase64){const raw=String(imageBase64||'').replace(/^data:[^;]+;base64,/,'');return Math.max(0,Math.floor(raw.length*.75))}
function estimateOutputBudget(imageBase64){const kb=imageBytes(imageBase64)/1024;let budget=DEFAULT_OUTPUT;if(kb<250)budget=Math.min(800,SAFE_OUTPUT_CEILING);else if(kb<500)budget=Math.min(850,SAFE_OUTPUT_CEILING);else budget=Math.min(900,SAFE_OUTPUT_CEILING);return Math.max(MIN_OUTPUT,Math.min(SAFE_OUTPUT_CEILING,budget))}
function classifyOutputLimit(message){const text=String(message||'').toLowerCase();return/output tokens per minute|otpm|requested\s+\d+.*(?:limit|max_tokens)|expected output tokens.*limit|reduce max_tokens|output.*token.*limit/.test(text)}
async function request(imageBase64,text,maxTokens,options){const started=Date.now(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),TIMEOUT),requestId=crypto.randomUUID();try{const safeMax=Math.max(MIN_OUTPUT,Math.min(SAFE_OUTPUT_CEILING,Math.floor(maxTokens))),body={model:MODEL.model,messages:[{role:'user',content:[{type:'text',text},{type:'image_url',image_url:{url:`data:image/jpeg;base64,${imageBase64}`}}]}],temperature:.05,top_p:.8,max_completion_tokens:safeMax,response_format:responseFormat()};if(MODEL.supports_reasoning_effort){body.reasoning_effort='none';body.reasoning_format='hidden'}const response=await fetch(GROQ_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${GROQ_API_KEY}`},body:JSON.stringify(body),signal:controller.signal}),latency=Date.now()-started;let data={};try{data=await response.json()}catch{}const choice=data?.choices?.[0]||{},usage=data?.usage||{},headers=response.headers,common={organization_id:options.organization_id,job_id:options.job_id,request_id:requestId,provider:'groq',model:MODEL.model,model_key:MODEL_KEY,purpose:options.purpose||'scan',prompt_version:SCAN_PIPELINE_VERSION,attempt:options.attempt||1,input_tokens:Number(usage.prompt_tokens||0),output_tokens:Number(usage.completion_tokens||0),latency_ms:latency,rate_limit_remaining_tokens:headers.get('x-ratelimit-remaining-tokens'),rate_limit_remaining_requests:headers.get('x-ratelimit-remaining-requests'),rate_limit_reset_tokens:headers.get('x-ratelimit-reset-tokens'),rate_limit_reset_requests:headers.get('x-ratelimit-reset-requests'),retry_after:headers.get('retry-after'),requested_output_tokens:safeMax};if(!response.ok){const message=data?.error?.message||`Groq request failed with ${response.status}`,outputLimit=response.status===429&&classifyOutputLimit(message);await safeLog({...common,http_status:response.status,success:false,finish_reason:'error',retry_reason:message});throw Object.assign(new Error(message),{status:response.status,code:outputLimit?'AI_OUTPUT_LIMIT':undefined,retryable:!outputLimit&&[408,429,500,502,503,504].includes(response.status),retryAfter:headers.get('retry-after'),requested_output_tokens:safeMax})}const content=choice?.message?.content||'',finishReason=choice?.finish_reason||'stop';await safeLog({...common,http_status:response.status,success:true,finish_reason:finishReason});if(!content.trim())throw Object.assign(new Error('Groq returned an empty vision response'),{code:'EMPTY_AI_RESPONSE',retryable:true});if(finishReason==='length')throw Object.assign(new Error('ARIA could not safely finish reading this register.'),{code:'AI_OUTPUT_TRUNCATED',retryable:false,requested_output_tokens:safeMax});return{data,attempt:options.attempt||1,usage,requestId,maxTokens:safeMax}}catch(error){if(error?.name==='AbortError')throw Object.assign(new Error('Vision provider timed out'),{code:'AI_TIMEOUT',retryable:true});throw error}finally{clearTimeout(timer)}}
function normalizeResult(result,mode,budget){const people=compactPeople(parseJSON(result?.data?.choices?.[0]?.message?.content||''));return{...result,data:{...result.data,choices:[{...(result.data?.choices?.[0]||{}),message:{...(result.data?.choices?.[0]?.message||{}),content:JSON.stringify({people})}}]},verification:{passes:1,extracted:people.length,mode},tokenPlan:{primary:budget,verification:null,recovery:RECOVERY_MAX,min_output:MIN_OUTPUT,safe_ceiling:SAFE_OUTPUT_CEILING,provider_ceiling:PROVIDER_OUTPUT_CEILING,max_people_per_page:MAX_PEOPLE_PER_PAGE,adaptive:true,deduplicated:true,row_verified:true},vision:'groq-single-pass-row-aware-name-format',pipeline_version:SCAN_PIPELINE_VERSION}}
export function getScanAdmission(){if(!GROQ_API_KEY)return{allowed:false,code:'AI_NOT_CONFIGURED',message:'ARIA scan is not configured.'};return{allowed:true,max_people_per_page:MAX_PEOPLE_PER_PAGE,max_output_tokens:SAFE_OUTPUT_CEILING,provider_output_ceiling:PROVIDER_OUTPUT_CEILING,safe_output_ceiling:SAFE_OUTPUT_CEILING,adaptive:true,row_verified:true,pipeline_version:SCAN_PIPELINE_VERSION}}
export async function callVisionWithRetry(imageBase64,_unused,onProgress=null,options={}){if(!GROQ_API_KEY)throw Object.assign(new Error('GROQ_API_KEY is missing'),{code:'AI_NOT_CONFIGURED',retryable:false});if(typeof imageBase64!=='string'||imageBase64.length<1000)throw Object.assign(new Error('Invalid scan image'),{code:'INVALID_IMAGE',retryable:false});const outputBudget=estimateOutputBudget(imageBase64);let lastError=null;for(let attempt=1;attempt<=MAX_RETRIES;attempt++){try{onProgress?.('reading_page');let primary;try{primary=await request(imageBase64,primaryPrompt(),outputBudget,{...options,attempt,purpose:'scan_primary'})}catch(error){if(error?.code!=='AI_OUTPUT_TRUNCATED'||outputBudget>=SAFE_OUTPUT_CEILING)throw error;onProgress?.('rereading_original');primary=await request(imageBase64,primaryPrompt(),SAFE_OUTPUT_CEILING,{...options,attempt:attempt+1,purpose:'scan_primary_recovery'})}const people=compactPeople(parseJSON(primary.data?.choices?.[0]?.message?.content||''));if(!people.length){onProgress?.('rereading_original');const recovery=await request(imageBase64,primaryPrompt(),RECOVERY_MAX,{...options,attempt:attempt+1,purpose:'scan_empty_recovery'}),recoveryPeople=compactPeople(parseJSON(recovery.data?.choices?.[0]?.message?.content||''));if(!recoveryPeople.length)throw Object.assign(new Error('No people could be extracted from the register image'),{code:'NO_PEOPLE_EXTRACTED',retryable:false});onProgress?.('finalizing_scan');return normalizeResult(recovery,'recovery',outputBudget)}onProgress?.('finalizing_scan');return normalizeResult(primary,'single_pass',outputBudget)}catch(error){lastError=error;if(error?.code==='AI_OUTPUT_LIMIT'||error?.code==='AI_OUTPUT_TRUNCATED'||attempt>=MAX_RETRIES||!error?.retryable)throw error;onProgress?.(error?.status===429?'provider_wait':'retrying');await sleep(retryDelay(error,attempt))}}throw lastError||new Error('Vision scan failed')}
