// lib/duplicateDetector.js
import pool from'./db';
import{fuzzyMatch,normalizeName}from'./scanValidation';
import normalizePhone from'./phoneUtils';
const REVIEW_MIN=62,STRONG_MIN=82;
function nameOf(p){return String(p.display_name||[p.first_name,p.last_name].filter(Boolean).join(' ')||p.first_name||'').trim()}
function phonesOf(p){const v=Array.isArray(p.phone_numbers)?p.phone_numbers:p.phone?[p.phone]:[];return[...new Set(v.map(x=>normalizePhone(typeof x==='string'?x:x?.normalized||x?.raw||x?.phone)).filter(Boolean))]}
function digits(v){return String(v||'').replace(/\D/g,'')}
function suffix(a,b){const x=digits(a),y=digits(b);if(!x||!y)return 0;for(let n=4;n>=1;n--)if(x.slice(-n)===y.slice(-n))return n;return 0}
function levenshtein(a,b){if(a===b)return 0;let x=a,y=b;if(x.length>y.length)[x,y]=[y,x];let prev=Array.from({length:x.length+1},(_,i)=>i);for(let j=1;j<=y.length;j++){const cur=[j];for(let i=1;i<=x.length;i++)cur[i]=Math.min(cur[i-1]+1,prev[i]+1,prev[i-1]+(x[i-1]===y[j-1]?0:1));prev=cur}return prev[x.length]}
function similarity(a,b){const m=Math.max(a.length,b.length);return m?1-levenshtein(a,b)/m:0}
function tokenScore(a,b){const ax=a.split(/\s+/).filter(Boolean),ay=b.split(/\s+/).filter(Boolean);if(!ax.length||!ay.length)return 0;let total=0;for(const t of ax){let best=0;for(const v of ay)best=Math.max(best,similarity(t,v));total+=best}return total/ax.length}
function nameDetails(a,b){const x=normalizeName(a),y=normalizeName(b);if(!x||!y)return{score:0,kind:'none'};if(x===y)return{score:100,kind:'exact'};const f=Math.round(Math.max(fuzzyMatch(x,y),tokenScore(x,y))*100);return{score:f,kind:f>=96?'near_exact':f>=88?'strong':f>=75?'possible':'weak'}}
function phoneDetails(a,b){let exact=0,best=0,pairs=[];for(const x of a)for(const y of b){if(x===y)exact++;const s=suffix(x,y);if(s>best)best=s;if(s>=2)pairs.push({a:x,b:y,last_digits_match:s})}let score=exact?100:best>=4?35:best===3?22:best===2?10:best===1?3:0;return{score,exact,best_suffix:best,pairs:[...pairs].slice(0,8)}}
function rareBonus(freq,name){const n=normalizeName(name);if(!n)return 0;return freq.get(n)<=1?5:freq.get(n)===2?3:0}
function verified(p){return p.identity_verification_status==='verified'||p.identity_verification_status==='disputed'&&false||p.metadata?.identity_verified===true}
function pair(a,b,freq){const na=nameOf(a),nb=nameOf(b),ns=nameDetails(na,nb),pa=phonesOf(a),pb=phonesOf(b),ps=phoneDetails(pa,pb),bothVerified=verified(a)&&verified(b),oneVerified=verified(a)||verified(b),sameName=ns.kind==='exact',sameFullPhone=ps.exact>0,rare=rareBonus(freq,na);let score=Math.min(100,Math.round(ns.score*.65+ps.score*.35+rare)),status='non_duplicate';if(sameFullPhone&&ns.score>=82)status='exact_duplicate';else if(score>=STRONG_MIN&&(!bothVerified||sameName||ps.score>=35))status='strong_duplicate';else if(score>=REVIEW_MIN&&ns.score>=75&&(!bothVerified||ps.score>=10||sameName))status='possible_duplicate';const evidence=[];if(ns.score)evidence.push(ns.kind==='exact'?'Exact normalized name':`Name similarity ${ns.score}%`);if(ps.exact)evidence.push(ps.exact===1?'Exact full phone match':`${ps.exact} exact full phone matches`);else if(ps.best_suffix>=2)evidence.push(`Phone shares last ${ps.best_suffix} digits`);if(rare)evidence.push('Rare name combination');if(oneVerified)evidence.push(bothVerified?'Both records are verified anchors.':'One record is already verified and is treated as the stronger identity anchor.');return{id:`${a.id}:${b.id}`,left:a,right:b,score,status,name_score:ns.score,phone_score:ps.score,verified_left:verified(a),verified_right:verified(b),evidence,phone_matches:ps.pairs,method:sameFullPhone?'name_and_full_phone':ps.best_suffix>=2?`name_plus_last_${ps.best_suffix}`:ns.kind+'_name',reason:status==='exact_duplicate'?'Exact identity evidence agrees across name and full phone.':status==='strong_duplicate'?'Strong duplicate evidence; human confirmation required before merge.':'Possible duplicate based on multiple identity signals.'}}
export async function detectDuplicates(orgId,{includeVerified=false}={}){if(!orgId)throw new Error('orgId required');const{rows}=await pool.query(`SELECT id,organization_id,first_name,last_name,display_name,phone,phone_numbers,type,status,confidence,metadata,living_truth,identity_verification_status,identity_verified_at,identity_verified_by,identity_verification_source,created_at,updated_at FROM people WHERE organization_id=$1 AND status='active' ORDER BY created_at,id`,[orgId]);const freq=new Map();for(const p of rows){const n=normalizeName(nameOf(p));freq.set(n,(freq.get(n)||0)+1)}const decisions=await pool.query(`SELECT person_a_id,person_b_id,decision FROM identity_pair_decisions WHERE organization_id=$1`,[orgId]);const decided=new Set(decisions.rows.filter(x=>x.decision==='not_duplicate').map(x=>{const a=String(x.person_a_id),b=String(x.person_b_id);return a<b?`${a}:${b}`:`${b}:${a}`}));const indexed=new Map();for(const p of rows){const ns=normalizeName(nameOf(p));const keys=new Set([ns,...ns.split(/\s+/).map(x=>x.slice(0,4)).filter(x=>x.length>=3)]);for(const key of keys){const list=indexed.get(key)||[];list.push(p);indexed.set(key,list)}}const pairs=new Map();for(const p of rows){const pPhones=phonesOf(p),n=normalizeName(nameOf(p)),candidates=new Map();for(const key of new Set([n,...n.split(/\s+/).map(x=>x.slice(0,4)).filter(x=>x.length>=3)]))for(const q of indexed.get(key)||[])if(q.id!==p.id)candidates.set(q.id,q);for(const q of rows){if(q.id===p.id)continue;const qPhones=phonesOf(q);if(pPhones.some(x=>qPhones.includes(x)))candidates.set(q.id,q)}for(const q of candidates.values()){const a=String(p.id)<String(q.id)?p:q,b=String(p.id)<String(q.id)?q:p,k=`${a.id}:${b.id}`;if(pairs.has(k)||decided.has(k))continue;const x=pair(a,b,freq);if(x.status!=='non_duplicate'||(includeVerified&&x.verified_left&&x.verified_right))pairs.set(k,x)}}const duplicates=[...pairs.values()].filter(x=>x.status!=='non_duplicate').sort((a,b)=>b.score-a.score);const groups=duplicates.map(x=>({id:x.id,score:x.score,status:x.status,members:[x.left,x.right].map(p=>({id:p.id,name:nameOf(p),phone:p.phone,phones:phonesOf(p),verified:verified(p),verification_status:p.identity_verification_status||'unverified'})),candidates:[x.left,x.right].map(p=>({id:p.id,name:nameOf(p),phone:p.phone,phones:phonesOf(p),verified:verified(p),verification_status:p.identity_verification_status||'unverified'})),evidence:x.evidence,reason:x.reason}));return{people_count:rows.length,duplicates,groups,verified_count:rows.filter(verified).length,unverified_count:rows.length-rows.filter(verified).length,detector_version:'v2-conservative-65-35-explicit-verification'}}
