// lib/hybridScanProvider.js
import sharp from 'sharp';
import crypto from 'crypto';
import { getModelConfig } from './modelRegistry';
import { logAIUsage } from './aiObserver';
const GROQ=process.env.GROQ_API_KEY,URL='https://api.groq.com/openai/v1/chat/completions',PRIMARY=getModelConfig('groq-qwen3.8-27b'),FALLBACK=getModelConfig('groq-qwen3.6-27b');
export const SCAN_PIPELINE_VERSION='v70-single-pass-vision';
const MAX=50,TIMEOUT=55000,MAX_RETRIES=1,clean=v=>String(v??'').replace(/\s+/g,' ').trim(),sleep=ms=>new Promise(r=>setTimeout(r,Math.max(0,ms)));
function decode(v){let s=String(v||'').trim(),m=s.match(/^data:([^;,]+);base64,(.*)$/is);if(m)s=m[2];s=s.replace(/\s/g,'').replace(/-/g,'+').replace(/_/g,'/');const b=Buffer.from(s,'base64');if(!b.length||b.length>4000000)throw Object.assign(Error('Invalid image.'),{code:'INVALID_IMAGE'});if(!(b[0]===255&&b[1]===216&&b[2]===255)&&!(b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71)&&!(b.slice(0,4).toString('ascii')==='RIFF'&&b.slice(8,12).toString('ascii')==='WEBP'))throw Object.assign(Error('Unsupported image format.'),{code:'INVALID_IMAGE'});return{buffer:b,base64:b.toString('base64')}}
const PROMPT=`You are the vision observer for NYEOCARE. Read the ENTIRE handwritten register as one physical document.\nDo not treat the page as OCR text. First inspect the whole page from TOP to BOTTOM and mentally map the physical rows, columns, indentation, vertical spacing, continuation lines, and which phone field sits beside or below each name.\nThen extract the logical people in top-to-bottom order. Return each person exactly once.\nA blank-name continuation line belongs to the preceding person only when its physical position, alignment and spacing clearly show continuation. A phone on a later named row belongs to that later row unless the physical page clearly proves otherwise.\nA person can have up to 2 visible phone numbers. Never borrow, invent, autocorrect, complete, shorten, or format a value because it looks more plausible. Preserve Nigerian/African/Christian names literally, including unfamiliar spellings.\nRead every visible phone digit literally. If any character is unclear, keep the best literal observation and flag it instead of repairing it.\nIgnore headers, totals, dates, page titles and unrelated notes.\nQWEN'S JOB ENDS AT OBSERVATION. Do not decide whether a person already exists in NYEOCARE, do not merge people, and do not create database identities.\nReturn only JSON. Coordinates are normalized to the full page: y and x are 0-1000. r is the physical/logical row order. For a continuation-only line, use the same r as its parent row.`;
const SCHEMA={type:'json_schema',json_schema:{name:'nyeocare_full_register',strict:true,schema:{type:'object',additionalProperties:false,properties:{people:{type:'array',maxItems:MAX,items:{type:'object',additionalProperties:false,properties:{r:{type:'integer',minimum:1,maximum:MAX},y:{type:'integer',minimum:0,maximum:1000},x:{type:'integer',minimum:0,maximum:1000},n:{type:'string'},p:{type:'array',maxItems:2,items:{type:'string'}},nc:{type:'number',minimum:0,maximum:100},pc:{type:'number',minimum:0,maximum:100},rc:{type:'number',minimum:0,maximum:100},ns:{type:'string',enum:['clear','ambiguous','unreadable']},ps:{type:'string',enum:['clear','ambiguous','unreadable']},rs:{type:'string',enum:['clear','ambiguous','unreadable']},f:{type:'array',items:{type:'string',enum:['digit_uncertain','missing_digit_possible','extra_digit_possible','number_visually_corrupted','continuation_uncertain','row_ownership_uncertain','name_uncertain','current_image_conflicts_with_learning']}},na:{type:'array',maxItems:3,items:{type:'string'}},e:{type:'string'}},required:['r','y','x','n','p','nc','pc','rc','ns','ps','rs','f','na','e']}}},required:['people']}}};
function parse(s){try{const x=JSON.parse(String(s||'').replace(/<think>[\s\S]*?<\/think>/gi,'').replace(/```json|```/gi,'').trim());return x&&Array.isArray(x.people)?x.people:null}catch{return null}}
function rl(h){const n=v=>{const s=String(v||'').trim().toLowerCase();if(!s)return 0;if(/^\d+(?:\.\d+)?$/.test(s))return Number(s);const m=s.match(/([\d.]+)\s*(ms|s|m|h)/);return m?Number(m[1])*({ms:.001,s:1,m:60,h:3600}[m[2]]):0};return{retryAfter:n(h.get('retry-after')),resetTokens:n(h.get('x-ratelimit-reset-tokens')),resetRequests:n(h.get('x-ratelimit-reset-requests')),remainingTokens:Number(h.get('x-ratelimit-remaining-tokens')),remainingRequests:Number(h.get('x-ratelimit-remaining-requests'))}}
function cooldown(r){return Math.min(120000,Math.max(0,Math.ceil(Math.max(r?.retryAfter||0,r?.resetTokens||0,r?.resetRequests||0)*1000)))}
async function prepare(buf){const s=sharp(buf).rotate(),m=await s.metadata();if(!m.width||!m.height)throw Object.assign(Error('Image dimensions are unreadable.'),{code:'INVALID_IMAGE'});return s.resize({width:Math.min(3200,m.width),withoutEnlargement:true}).normalize().sharpen({sigma:1.05}).jpeg({quality:94,mozjpeg:true}).toBuffer()}
async function request(image,opt,model,attempt){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),TIMEOUT),id=crypto.randomUUID(),started=Date.now();try{const body={model:model.model,messages:[{role:'user',content:[{type:'text',text:PROMPT},{type:'image_url',image_url:{url:`data:image/jpeg;base64,${image}`}}]}],temperature:0,top_p:.9,reasoning_effort:'high',reasoning_format:'hidden',max_completion_tokens:Math.min(6500,model.max_completion_tokens),response_format:model===PRIMARY?SCHEMA:{type:'json_object'}};const r=await fetch(URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${GROQ}`},body:JSON.stringify(body),signal:ac.signal}),d=await r.json().catch(()=>({})),u=d?.usage||{},rate=rl(r.headers);await logAIUsage({organization_id:opt?.organization_id,job_id:opt?.job_id,request_id:id,model_key:model===PRIMARY?'groq-qwen3.8-27b':'groq-qwen3.6-27b',provider:'groq',model:model.model,purpose:'scan_full_page',prompt_version:SCAN_PIPELINE_VERSION,attempt,latency_ms:Date.now()-started,input_tokens:Number(u.prompt_tokens||0),output_tokens:Number(u.completion_tokens||0),reasoning_tokens:Number(u.completion_tokens_details?.reasoning_tokens||0),total_tokens:Number(u.total_tokens||0),http_status:r.status,success:r.ok,finish_reason:d?.choices?.[0]?.finish_reason||null,rate_limit_remaining_tokens:r.headers.get('x-ratelimit-remaining-tokens'),rate_limit_remaining_requests:r.headers.get('x-ratelimit-remaining-requests'),rate_limit_reset_tokens:r.headers.get('x-ratelimit-reset-tokens'),rate_limit_reset_requests:r.headers.get('x-ratelimit-reset-requests'),retry_after:r.headers.get('retry-after')}).catch(()=>{});if(!r.ok)throw Object.assign(Error(d?.error?.message||`Groq request failed (${r.status})`),{code:r.status===429?'AI_RATE_LIMIT':r.status===404?'AI_MODEL_UNAVAILABLE':'AI_PROVIDER_ERROR',status:r.status,provider:model.model,requestId:id,...rate,cooldownSeconds:cooldown(rate)/1000});if(d?.choices?.[0]?.finish_reason==='length')throw Object.assign(Error('Vision output was truncated.'),{code:'AI_OUTPUT_TRUNCATED',provider:model.model,requestId:id});const people=parse(d?.choices?.[0]?.message?.content);if(!people)throw Object.assign(Error('Vision returned invalid JSON.'),{code:'AI_INVALID_RESPONSE',provider:model.model,requestId:id});return{people,model:model.model,requestId:id,rate}}catch(e){if(e?.name==='AbortError')throw Object.assign(Error('Vision timed out while reading the full page.'),{code:'AI_TIMEOUT',provider:model.model,requestId:id});throw e}finally{clearTimeout(timer)}}
function cleanPeople(raw){const rows=[];for(const x of raw){if(!x||typeof x!=='object')continue;const r=Number(x.r),y=Math.max(0,Math.min(1000,Number(x.y)||0)),p=Array.isArray(x.p)?x.p.map(clean).filter(Boolean).slice(0,2):[],n=clean(x.n);if(!n&&!p.length)continue;rows.push({...x,r:Number.isInteger(r)&&r>0?r:null,y,x:Math.max(0,Math.min(1000,Number(x.x)||0)),n,p,f:Array.isArray(x.f)?x.f:[],na:Array.isArray(x.na)?x.na.slice(0,3):[],e:clean(x.e)})}rows.sort((a,b)=>a.y-b.y||(a.x||0)-(b.x||0));return rows.slice(0,MAX)}
function mergeLogicalRows(raw){const rows=cleanPeople(raw),out=[];for(const row of rows){const prev=out[out.length-1],rowSame=row.r&&prev?.r&&row.r===prev.r,dy=prev?row.y-prev.y:999,continuation=!row.n&&row.p.length&&prev?.n&&dy>=0&&dy<=75;if(prev&&continuation&&(rowSame||dy<=45)){for(const p of row.p)if(!prev.p.some(q=>q===p))prev.p.push(p);prev.p=prev.p.slice(0,2);prev.f=[...new Set([...(prev.f||[]),...(row.f||[]),'continuation_uncertain'])];prev.e=[prev.e,row.e,'blank-name continuation physically below previous row'].filter(Boolean).join('; ');continue}out.push(row)}return out.map((x,i)=>({...x,r:Number.isInteger(x.r)?x.r:i+1,flags:x.f}))}
async function callOne(image,opt){let last=null;for(let attempt=1;attempt<=1+MAX_RETRIES;attempt++){try{return await request(image,opt,PRIMARY,attempt)}catch(e){last=e;if(e.code==='AI_RATE_LIMIT'&&attempt<=MAX_RETRIES){const ms=cooldown(e);if(ms>0)await sleep(ms);continue}if(['AI_MODEL_UNAVAILABLE','AI_PROVIDER_ERROR','AI_TIMEOUT'].includes(e.code)&&FALLBACK?.model)try{return await request(image,opt,FALLBACK,20+attempt)}catch(f){last=f}break}}throw last||Error('Vision request failed')}
export function getScanAdmission(){return GROQ?{allowed:true,max_people_per_page:MAX,pipeline_version:SCAN_PIPELINE_VERSION,model:PRIMARY.model,regions:1,crosscheck_model:null,reasoning:'high'}:{allowed:false,code:'AI_NOT_CONFIGURED',message:'ARIA scan is not configured.'}}
export async function callVisionWithRetry(img,_unused,onProgress=null,opt={}){if(!GROQ)throw Object.assign(Error('GROQ_API_KEY is missing'),{code:'AI_NOT_CONFIGURED'});const image=decode(img),prepared=await prepare(image.buffer);onProgress?.('reading_full_page');const result=await callOne(prepared.toString('base64'),opt);onProgress?.('reconstructing_rows');const people=mergeLogicalRows(result.people);if(!people.length)throw Object.assign(Error('No readable register rows were found.'),{code:'AI_INVALID_RESPONSE'});onProgress?.('validating_extraction');return{data:{choices:[{message:{content:JSON.stringify({people})},finish_reason:'stop'}]},verification:{passes:1,extracted:people.length,mode:'single_pass_rate_aware_vision',reviewed:false,agreement:null,disagreements:[],regions:1,crosscheck_model:null},tokenPlan:{regions:1,crosscheck:0,recovery:'single full-page Qwen observation with one controlled transient retry and model fallback only on provider failure'},vision:`single-${result.model}`,pipeline_version:SCAN_PIPELINE_VERSION,request_id:result.requestId,provider:'groq',model:result.model,rate_limit:result.rate||null,diagnostic:{mode:'single_pass_rate_aware_vision',rows:people.length,model:result.model}}}
