// lib/scanState.js
export const INTERNAL_STATES={QUEUED:'queued',ANALYSING:'analysing',EXTRACTING:'extracting',VALIDATING:'validating',MATCHING:'matching',SAVING:'saving',COMPLETED:'completed',RETRYING:'retrying',FAILED:'failed',TIMED_OUT:'timed_out',CANCELLED:'cancelled'};
export const PROGRESS_STAGES={enhancing:'enhancing',layout_analysis:'layout_analysis',reading_handwriting:'reading_handwriting',verifying_rows:'verifying_rows',validating:'validating',matching_community:'matching_community',building_memory:'building_memory',complete:'complete'};
export function ariaMessageForState(state,progress){
 const p={enhancing:'ARIA is preparing the image…',layout_analysis:'ARIA is examining the register structure…',reading_handwriting:'ARIA is reviewing the handwriting…',verifying_rows:'ARIA is checking that every phone number belongs to the correct row…',validating:'ARIA is validating the extracted records…',matching_community:'ARIA is comparing the records with your community…',building_memory:'ARIA is remembering the verified people…',complete:'ARIA has finished safely…'};
 const s={queued:'ARIA is preparing to read the register…',analysing:'ARIA is examining the register…',extracting:'ARIA is reading the register…',validating:'ARIA is checking every entry carefully…',matching:'ARIA is matching people with your community…',saving:'ARIA is remembering the verified changes…',completed:'ARIA has finished!',retrying:'ARIA is taking a little longer than usual…',failed:'ARIA could not complete this scan safely.',timed_out:'ARIA took too long and stopped safely.',cancelled:'Scan was cancelled.'};
 return p[progress]||s[state]||'ARIA is working…';
}
export function dbStatusFromInternal(state){return{queued:'pending',analysing:'processing',extracting:'processing',validating:'processing',matching:'processing',saving:'processing',completed:'complete',retrying:'retrying',failed:'failed',timed_out:'failed',cancelled:'failed'}[state]||'processing'}
