// lib/scanVisionAudit.js
import{getModelConfig}from'./modelRegistry';import{logAIUsage}from'./aiObserver';import crypto from'crypto';
const KEY=process.env.GROQ_API_KEY,MODEL_KEY='groq-qwen3.8-27b',MODEL=getModelConfig(MODEL_KEY),URL='https://api.groq.com/openai/v1/chat/completions',MAX=50,VERIFY_TOKENS=2600,SCHEMA={type:'object',additionalProperties:false,properties:{people:{type:'array',items:{type:'object',additionalProperties:false,properties:{r:{type:'integer',minimum:1,maximum:MAX},n:{type:'string'},p:{type:'array',items:{type:'string'}},f:{type:'array',items:{type:'string',enum:['digit_uncertain','missing_digit_possible','extra_digit_possible','continuation_uncertain','row_ownership_uncertain','number_visually_corrupted','name_uncertain','unfamiliar_but_plausible']}},a:{type:'array',items:{type:'string'}}},required:['r','n','p','f','a']}}},required:['people']};
const PROMPT=`NYEOCARE SECOND-PASS VISUAL AUDITOR. The original register image is the source of truth. You are auditing an untrusted first-pass transcription. Re-read the IMAGE from scratch and return the corrected physical register transcription as compact JSON only. Do not trust the draft when it conflicts with pixels.

CORE OBJECTIVE: achieve human-level row ownership. First understand the WHOLE PAGE, then map the PHYSICAL person rows from top to bottom. A person row is defined by the visual relationship of the name and its associated writing, not by how many text lines appear. A single person may occupy multiple vertical handwriting lines. One person may have TWO phone numbers stacked on separate lines. Therefore NEVER assume one visible phone line = one person. If a second phone is directly beneath a person's name/phone area and the next person's name begins lower down, keep that second phone with the earlier person. This is valid even when the phone occupies the next text line.

SPATIAL REASONING: inspect alignment, indentation, horizontal position, vertical proximity, whitespace, ruled lines, columns, arrows, brackets, circles, underlines, connecting strokes, continuation marks and where strokes begin/end. Lines are not automatically row boundaries. An arrow/line may explicitly connect a name to a phone or move a phone to a prior row. Follow a connector only when its geometry supports the connection. Never steal a phone from a row merely because another name appears nearby.

COUNTING: count physical PEOPLE, not text lines. Return one object for every readable person row, in visual top-to-bottom order. A page can legitimately contain N names and N+1 phone values when one person has two numbers. Do not force equal name/phone counts. Never merge neighboring people and never shift all later phones because one person has an extra phone.

PHONES: read EVERY digit literally from the image. Re-check each number character-by-character in both directions. Never invent, repair, normalize-to-plausibility, pad, truncate, transpose or borrow digits. Nigerian numbers commonly have 11 local digits, but this is only a sanity check; the IMAGE wins. Preserve a visibly malformed sequence and flag digit uncertainty instead of silently fixing it. Put all phone values physically belonging to the same person in p, in their visual order, maximum 2.

NAMES: preserve what is visibly written, including titles, hyphens and apostrophes. Recognize Nigerian, African and English names across major regional naming patterns. An unfamiliar but visually plausible name is NOT garbage and must be preserved; flag unfamiliar_but_plausible only when helpful. Do not replace an unfamiliar name with a familiar name. If letters are genuinely unclear, keep the best visible reading and flag name_uncertain with at most 2 alternative readings in a.

ANTI-HALLUCINATION: never use a nearby/familiar name or phone to complete missing pixels. Never assume the next phone belongs to the next name. Never convert a partial phone into a plausible 11-digit number. Never create a phone because a row has no phone.

DRAFT TO AUDIT (UNTRUSTED):
__DRAFT__

OUTPUT: ONLY {"people":[{"r":1,"n":"exact visible name","p":["exact visible phone"],"f":[],"a":[]}]}. Every object must contain r,n,p,f,a. No markdown. No explanation. No confidence scores. Physical order wins.`;
function parse(x){if(typeof x!=='string')return null;const s=x.replace(/<think>[\s\S]*?<\/think>/gi,'').replace(/```json|```/gi,'').trim();try{const v=JSON.parse(s);return v&&Array.isArray(v.people)?v:null}catch{return null}}
function rl(h){return{remainingTokens:Number(h.get('x-ratelimit-remaining-tokens')),remainingRequests:Number(h.get('x-ratelimit-remaining-requests')),resetTokens:h.get('x-ratelimit-reset-tokens')||null,resetRequests:h.get('x-ratelimit-reset-requests')||null,retryAfter:h.get('retry-after')||null}}
export async function auditScanVision(img,primary,opt={}){if(!KEY)return{ok:false,reason:'not_configured'};const draft=JSON.stringify(primary?.data?.choices?.[0]?.message?.content?parse(primary.data.choices[0].message.content):primary?.people||{});const prompt=PROMPT.replace('__DRAFT__',draft.slice(0,14000)),rid=crypto.randomUUID(),st=Date.now(),body={model:MODEL.model,messages:[{role:'user',content:[{type:'text',text:prompt},{type:'image_url',image_url:{url:`data:image/jpeg;base64,${img}`}}]}],temperature:.1,top_p:.9,reasoning_effort:'none',reasoning_format:'hidden',max_completion_tokens:VERIFY_TOKENS,response_format:{type:'json_schema',json_schema:{name:'nyeocare_register_audit',strict:true,schema:SCHEMA}}};try{const r=await fetch(URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${KEY}`},body:JSON.stringify(body)}),d=await r.json().catch(()=>({})),content=d?.choices?.[0]?.message?.content||'',parsed=parse(content),status=r.status,finish=d?.choices?.[0]?.finish_reason||null,usage={input:Number(d?.usage?.prompt_tokens||0),output:Number(d?.usage?.completion_tokens||0),reasoning:Number(d?.usage?.completion_tokens_details?.reasoning_tokens??0),total:Number(d?.usage?.total_tokens||0)},telemetry=rl(r.headers);await logAIUsage({organization_id:opt.organization_id,job_id:opt.job_id,request_id:rid,model_key:MODEL_KEY,provider:'groq',model:MODEL.model,purpose:'scan_visual_audit',prompt_version:'v57-spatial-audit',attempt:1,latency_ms:Date.now()-st,input_tokens:usage.input,output_tokens:usage.output,reasoning_tokens:usage.reasoning,total_tokens:usage.total,http_status:status,success:r.ok,finish_reason:finish,rate_limit_remaining_tokens:r.headers.get('x-ratelimit-remaining-tokens'),rate_limit_remaining_requests:r.headers.get('x-ratelimit-remaining-requests'),rate_limit_reset_tokens:r.headers.get('x-ratelimit-reset-tokens'),rate_limit_reset_requests:r.headers.get('x-ratelimit-reset-requests'),retry_after:r.headers.get('retry-after')}).catch(e=>console.error('[AI-AUDIT] telemetry write failed',e?.message||e));if(!r.ok||!parsed?.people?.length)return{ok:false,status,finish_reason:finish,rate_limit:telemetry,provider_message:d?.error?.message||null};if(parsed.people.length>MAX)return{ok:false,status,finish_reason:finish,rate_limit:telemetry,reason:'too_many_rows'};return{ok:true,people:parsed.people,verification:{passes:2,mode:'primary_plus_spatial_audit',audit_rows:parsed.people.length,finish_reason:finish,request_id:rid},rate_limit:telemetry,usage}}catch(e){return{ok:false,reason:e?.message||'audit_failed'}}}
