// lib/scanValidation.js
import normalizePhone from'./phoneUtils';
import{canonicalNameSuggestion}from'./nameIntelligence';
export const MAX_PEOPLE_PER_SCAN=50;
const HONORIFICS=new Set(['sis','sister','bro','brother','mr','mrs','miss','ms','pastor','past','pst','dr','rev','reverend','elder','deacon','deaconess','chief','bishop','apostle','prophet','minister','evangelist','canon','father','archbishop']);
const HEADERS=new Set(['name','names','phone','phones','mobile','number','numbers','telephone','contact','contacts','member','members','person','people']);
const REASONING_PHRASES=["let's",'re-read','look at','illegible','faint','carefully','seems to be','appears to be','i think','i see','maybe','perhaps'];
export function normalizeName(name){if(!name)return'';return String(name).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/^\s*\d+[\.\)]\s*/,'').replace(/\*\*/g,' ').replace(/\b(sis|sister|bro|brother|mr|mrs|miss|ms|pastor|past|pst|dr|rev|reverend|elder|deacon|deaconess|chief|bishop|apostle|prophet|minister|evangelist|canon|father|archbishop)\b/g,' ').replace(/[^a-z\s'\-]/g,' ').replace(/\s+/g,' ').trim()}
export{normalizePhone};
function titleToken(v){return String(v||'').split(/(-|')/).map(x=>/^[a-z]/i.test(x)?x.charAt(0).toUpperCase()+x.slice(1).toLowerCase():x).join('')}
export function normalizeDisplayName(name){const raw=String(name||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();if(!raw)return{display:'',core:'',honorific:null};const parts=raw.split(' ').filter(Boolean);let honorific=null;if(parts.length){const key=parts[0].toLowerCase().replace(/[.,]/g,'');if(HONORIFICS.has(key))honorific=titleToken(parts.shift())}const core=parts.map(titleToken).join(' ').trim();return{display:[honorific,core].filter(Boolean).join(' '),core,honorific}}
function similarity(a,b){if(a===b)return 1;if(!a||!b)return 0;const prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const cur=[i];for(let j=1;j<=b.length;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<cur.length;j++)prev[j]=cur[j]}return 1-prev[b.length]/Math.max(a.length,b.length)}
export function fuzzyMatch(a,b){const x=normalizeName(a),y=normalizeName(b);if(!x||!y)return 0;if(x===y)return 1;const ax=x.split(/\s+/),ay=y.split(/\s+/);let tokenTotal=0;for(const t of ax){let best=0;for(const v of ay)best=Math.max(best,similarity(t,v));tokenTotal+=best}return Math.max(similarity(x,y),tokenTotal/ax.length)}
function corruptedName(name){if(name===null||name===undefined)return true;const n=String(name).trim(),lower=n.toLowerCase();if(!n||n.length>100||HEADERS.has(lower))return true;if(REASONING_PHRASES.some(x=>lower.includes(x)))return true;if(/^\d[\d\s()+\-./]*$/.test(n))return true;if((n.match(/\d/g)||[]).length>Math.max(2,Math.ceil(n.length*.35)))return true;return!/[a-zA-ZÀ-ÖØ-öø-ÿ]/.test(n)}
function phoneList(raw){const value=raw?.p??raw?.phone??raw?.phones;if(Array.isArray(value))return value.map(v=>String(v??'').trim()).filter(Boolean).slice(0,4);if(value==null)return[];const s=String(value).trim();return s?[s]:[]}
function validatePhone(phone){const normalized=normalizePhone(phone);if(!normalized)return{valid:false,reason:'phone_not_readable'};const digits=normalized.replace(/\D/g,'');if(digits.length<10||digits.length>15)return{valid:false,reason:'invalid_phone_length'};if(/^(\d)\1+$/.test(digits))return{valid:false,reason:'invalid_phone_format'};return{valid:true,phone:normalized}}
function parseStrictJSON(text){if(!text||typeof text!=='string')return null;const cleaned=text.replace(/<think>[\s\S]*?<\/think>/gi,'').replace(/```json/gi,'').replace(/```/g,'').trim();try{const parsed=JSON.parse(cleaned);if(Array.isArray(parsed))return parsed;if(parsed&&Array.isArray(parsed.people))return parsed.people}catch{}return null}
function splitName(value){const normalized=normalizeDisplayName(value),parts=normalized.core.split(/\s+/).filter(Boolean);return{first_name:parts.shift()||'',last_name:parts.join(' '),honorific:normalized.honorific,display:normalized.display}}
function digits(v){return String(v||'').replace(/\D/g,'')}
function suffixMatch(a,b){const x=digits(a),y=digits(b);if(!x||!y)return 0;let n=0;for(let i=1;i<=4;i++){if(x.slice(-i)===y.slice(-i))n=i;else break}return n}
function reasonInfo(reasons,nameSuggestions=[]){if(reasons.includes('duplicate_identity_in_scan'))return{reason:'The same name and full phone appear again.',suggestion:'Check whether the repeated row is a duplicate or a real second record.'};if(reasons.includes('shared_phone_in_scan'))return{reason:'This full phone number is assigned to another row.',suggestion:'Check the original register to confirm which person the number belongs to.'};if(reasons.includes('name_needs_verification'))return{reason:nameSuggestions.length?`The name may be a different reading of ${nameSuggestions[0].name}.`:'Name needs checking.',suggestion:'Check the original register and correct the name if necessary.'};const map={phone_number_not_safely_validated:['Phone number needs checking.','Compare the number with the original register before confirming it.'],too_many_phone_numbers:['More than two phone numbers were found.','Keep only the numbers visibly assigned to this person.'],phone_missing:['No phone number was safely read.','Check whether a phone number is visibly assigned to this person.']};for(const reason of reasons)if(map[reason])return{reason:map[reason][0],suggestion:map[reason][1]};return{reason:'ARIA found something that needs your attention.',suggestion:'Review the original register and confirm the information.'}}
export function parseScanOutput(rawContent){const people=parseStrictJSON(rawContent);if(!Array.isArray(people))return{valid:false,error:'AI response was not valid JSON.',people:[]};if(people.length>MAX_PEOPLE_PER_SCAN)return{valid:false,error:`Scan exceeds the ${MAX_PEOPLE_PER_SCAN}-person page limit.`,people:[]};return{valid:true,people}}
export async function validateScanOutput(rawContent,orgId,programName,jobId,options={}){const parsed=parseScanOutput(rawContent);if(!parsed.valid)return{valid:false,error:parsed.error,people:[],needsReview:[],rejected:[],total_extracted:0,total_valid:0};const rejected=[],needsReview=[],people=[],seenIdentity=new Map(),seenPhones=new Map();
for(let index=0;index<parsed.people.length;index++){const raw=parsed.people[index];if(!raw||typeof raw!=='object'){rejected.push({name:'',phone:'',reason:'Invalid person object',row_number:index+1});continue}const rawName=String(raw.n??raw.name??'').trim(),rawPhones=phoneList(raw),parts=splitName(rawName),cleanDisplay=parts.display||rawName,nameKey=normalizeName(cleanDisplay),rowNumber=index+1,reasons=[];if(corruptedName(rawName)||!nameKey)reasons.push('name_needs_verification');if(rawPhones.length>2)reasons.push('too_many_phone_numbers');const phoneResults=rawPhones.map(validatePhone),validPhones=phoneResults.filter(x=>x.valid).map(x=>x.phone);if(!rawPhones.length)reasons.push('phone_missing');if(rawPhones.some((_,i)=>!phoneResults[i]?.valid))reasons.push('phone_number_not_safely_validated');const hasIdentityPhone=validPhones.length>0,identityKey=hasIdentityPhone?nameKey+'|'+[...validPhones].sort().join('|'):null;if(identityKey&&seenIdentity.has(identityKey))reasons.push('duplicate_identity_in_scan');for(const p of validPhones)if(seenPhones.has(p)&&!reasons.includes('duplicate_identity_in_scan'))reasons.push('shared_phone_in_scan');const suggestion=canonicalNameSuggestion(cleanDisplay||rawName),candidate={name:cleanDisplay,raw_name:rawName,display_name:cleanDisplay,first_name:parts.first_name,last_name:parts.last_name,honorific:parts.honorific,phone:validPhones[0]||null,phones:validPhones,rawPhone:rawPhones[0]||null,rawPhones,confidence:0,name_confidence:0,phone_confidence:0,model_confidence:0,row_number:rowNumber,phone_relation:'same_row',link_evidence:null,verification_status:reasons.length?'review':'extracted',verification_reasons:[...new Set(reasons)],relationship_stage:String(raw.relationship_stage||'first_time_visitor').trim()};
const priorPhones=people.flatMap(x=>x.phones||[]);candidate.same_page_phone_suffix_matches=validPhones.flatMap(p=>priorPhones.map(other=>({phone:other,last_digits_match:suffixMatch(p,other)})).filter(x=>x.last_digits_match>=2)).slice(0,8);people.push(candidate);if(identityKey)seenIdentity.set(identityKey,true);validPhones.forEach(p=>seenPhones.set(p,true));if(reasons.length){const info=reasonInfo(reasons,suggestion);needsReview.push({status:'needs_decision',extracted_name:cleanDisplay||rawName||null,display_name:cleanDisplay||rawName||null,extracted_phone:validPhones[0]||null,extracted_phones:validPhones,raw_phones:rawPhones,row_number:rowNumber,reasons:[...new Set(reasons)],reason:info.reason,suggestion:info.suggestion,name_suggestions:suggestion,incoming:{name:cleanDisplay||rawName||null,phone:validPhones[0]||null,phones:validPhones,rawPhones}})}}
return{valid:true,people,needsReview,rejected,total_extracted:people.length,total_valid:people.length}}
