// lib/scanReviewStore.js
function phonesFor(person){const v=Array.isArray(person?.phones)?person.phones:Array.isArray(person?.phone_numbers)?person.phone_numbers:person?.phone?[person.phone]:[];return v.map(x=>typeof x==='string'?x:x?.normalized||x?.raw||x?.phone).filter(Boolean).slice(0,2)}
export async function createScanReview(client,{organizationId,scanJobId,scanEvidenceId=null,actorId=null,programName=null,person,decision,review=null}){
 const reasons=[...new Set([...(review?.reasons||[]),...(decision?.field_review_reasons||[]),...(decision?.status==='conflict'?['identity_conflict']:decision?.status==='needs_decision'?['identity_needs_decision']:[])])];
 const reason=review?.reason||(decision?.status==='conflict'?'More than one existing person matches this observation.':decision?.status==='needs_decision'?'ARIA found a plausible existing person but the identity is not decisive.':'ARIA found field evidence that needs review.');
 const suggestion=review?.suggestion||'Compare the original register with the suggested identity before deciding.';
 const candidates=(decision?.candidates||[]).slice(0,6);
 const evidence={extracted:person,evidence:decision?.evidence||null,identity_match:decision?.identity_match||'none',field_review_reasons:decision?.field_review_reasons||[],candidate_ids:decision?.candidate_ids||[]};
 const q=await client.query(`INSERT INTO scan_review_items(organization_id,scan_job_id,scan_evidence_id,row_number,raw_name,raw_phones,extracted_name,extracted_phones,normalized_name,normalized_phones,status,review_reasons,reason,suggestion,evidence,candidates,proposed_person_id,program_name,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8::jsonb,$9,$10::jsonb,'pending',$11::jsonb,$12,$13,$14::jsonb,$15::jsonb,$16,$17,$18,NOW(),NOW()) RETURNING id`,[organizationId,scanJobId,scanEvidenceId,Number(person.row_number)||null,person.raw_name||null,JSON.stringify(person.rawPhones||[]),person.name||null,JSON.stringify(phonesFor(person)),person.name?String(person.name):null,JSON.stringify(phonesFor(person)),JSON.stringify(reasons),reason,suggestion,JSON.stringify(evidence),JSON.stringify(candidates),decision?.best_candidate_id||null,programName,actorId]);
 return q.rows[0].id;
}
