// lib/scanIdentityResolver.js
import{normalizeName,fuzzyMatch}from'./scanValidation';
const digits=v=>String(v??'').replace(/\D/g,''),phones=p=>{const a=Array.isArray(p?.phones)?p.phones:Array.isArray(p?.phone_numbers)?p.phone_numbers:p?.phone?[p.phone]:[];return a.map(x=>digits(typeof x==='object'?x.normalized||x.raw:x)).filter(Boolean)};
const name=v=>normalizeName(v).replace(/[^a-z0-9]/g,''),score=(a,b)=>fuzzyMatch(a,b);
function indexPeople(rows){const byPhone=new Map(),byName=new Map();for(const p of rows){for(const x of phones(p)){const a=byPhone.get(x)||[];a.push(p);byPhone.set(x,a)}const n=name(p.display_name);if(n){const a=byName.get(n)||[];a.push(p);byName.set(n,a)}}return{byPhone,byName}}
export async function loadIdentityIndex(client,orgId){const q=await client.query(`SELECT id,display_name,first_name,last_name,type,phone,phone_numbers,living_truth,metadata FROM people WHERE organization_id=$1 AND status='active'`,[orgId]);return{people:q.rows,...indexPeople(q.rows)}}
function exactPair(row,index){const n=name(row.display_name),ps=phones(row);if(!n||!ps.length)return null;for(const p of index.byName.get(n)||[])if(ps.some(x=>phones(p).includes(x)))return{decision:'EXISTING',match_type:'NAME_PHONE_EXACT',confidence:100,person:p};return null}
function resolveRow(row,index){const n=name(row.display_name),ps=phones(row),pair=exactPair(row,index);if(pair)return pair;const candidates=new Map();for(const ph of ps){const matches=index.byPhone.get(ph)||[];if(matches.length>1)for(const p of matches)candidates.set(p.id,{person:p,phone_exact:true,shared_phone:true,name_score:score(row.display_name,p.display_name)});else for(const p of matches)candidates.set(p.id,{person:p,phone_exact:true,shared_phone:false,name_score:score(row.display_name,p.display_name)})}for(const p of index.byName.get(n)||[]){const ns=score(row.display_name,p.display_name),shared=ps.some(x=>phones(p).includes(x)),old=candidates.get(p.id);candidates.set(p.id,{person:p,phone_exact:shared,shared_phone:old?.shared_phone||false,name_score:Math.max(ns,old?.name_score||0)})}const ranked=[...candidates.values()].sort((a,b)=>(Number(b.phone_exact)-Number(a.phone_exact))||(b.name_score-a.name_score));if(!ranked.length)return{decision:'NEW',match_type:'NO_MATCH',confidence:0,person:null};const best=ranked[0],samePhone=ranked.filter(x=>x.phone_exact);if(best.phone_exact&&samePhone.length===1&&best.name_score>=.84)return{decision:'EXISTING',match_type:'PHONE_EXACT_NAME_STRONG',confidence:Math.round(84+best.name_score*16),person:best.person,name_score:best.name_score};if(best.phone_exact)return{decision:'REVIEW',match_type:samePhone.length>1?'PHONE_SHARED_OR_AMBIGUOUS':'PHONE_EXACT_NAME_CONFLICT',confidence:Math.round(best.name_score*100),person:best.person,name_score:best.name_score,reason:samePhone.length>1?'phone_belongs_to_multiple_people':'phone_matches_existing_but_name_conflicts'};const second=ranked[1];if(best.name_score>=.93&&(!second||second.name_score<best.name_score-.04))return{decision:'REVIEW',match_type:'NAME_STRONG_PHONE_CHANGED',confidence:Math.round(best.name_score*100),person:best.person,name_score:best.name_score,reason:'name_matches_but_phone_does_not'};if(best.name_score>=.82)return{decision:'REVIEW',match_type:'POSSIBLE_EXISTING',confidence:Math.round(best.name_score*100),person:best.person,name_score:best.name_score,reason:'possible_existing_person'};return{decision:'NEW',match_type:'NO_SAFE_MATCH',confidence:Math.round(best.name_score*100),person:null,name_score:best.name_score}}
export function reconcileScanRows(rows,index){const seen=new Map(),out=[];for(const row of rows){const key=name(row.display_name)+'|'+phones(row).sort().join(',');if(key!=='|'&&seen.has(key)){out.push({...row,identity:{decision:'DUPLICATE_IN_SCAN',match_type:'SCAN_ROW_DUPLICATE',duplicate_of_row:seen.get(key)}});continue}if(key!=='|')seen.set(key,row.row_number);const r=resolveRow(row,index);out.push({...row,identity:{...r,person:r.person?{id:r.person.id,name:r.person.display_name,phones:phones(r.person)}:null}})}return out}
export function summarizeIdentity(rows){const s={extracted:rows.length,new_people:0,already_known:0,duplicates_in_scan:0,needs_review:0};for(const r of rows){const d=r.identity?.decision;if(d==='NEW')s.new_people++;else if(d==='EXISTING')s.already_known++;else if(d==='DUPLICATE_IN_SCAN')s.duplicates_in_scan++;else if(d==='REVIEW')s.needs_review++}return s}
