// lib/visionProcessor.js
import pool from './db';
import{callVisionWithRetry,SCAN_PIPELINE_VERSION as PIPELINE_VERSION}from'./aiProvider';
import{validateScanOutput}from'./scanValidation';
import{INTERNAL_STATES,dbStatusFromInternal}from'./scanState';
import crypto from 'crypto';
import{handleScanEvent,directAriaEvent}from'./aria/director';
import{emitAriaEvent}from'./aria/eventEmitter';
import{createScanReview}from'./scanReviewStore';
import{buildScanContext}from'./scanContext';
export const SCAN_PIPELINE_VERSION=PIPELINE_VERSION;
const TERMINAL=[INTERNAL_STATES.COMPLETED,INTERNAL_STATES.FAILED,INTERNAL_STATES.TIMED_OUT];
async function updateJobState(client,jobId,state,progress,result,attemptCount,provider,startTime){const terminal=TERMINAL.includes(state),now=new Date(),db=client||pool,errorCode=result?.error?.code||null,fields={status:dbStatusFromInternal(state),progress:progress||null,heartbeat:now,last_progress_at:now,attempt_count:attemptCount??0,provider_used:provider||null,completed_at:terminal?now:undefined,duration_ms:terminal?Math.max(0,Math.round(now-startTime)):undefined,error_code:terminal?errorCode:null,result:result==null?undefined:result},entries=Object.entries(fields).filter(([,v])=>v!==undefined),set=entries.map(([key],i)=>`${key}=$${i+2}`).join(',');await db.query(`UPDATE scan_jobs SET ${set} WHERE id=$1`,[jobId,...entries.map(([,v])=>v)])}
function rateLimitMessage(err){const provider=String(err?.provider||'AI vision provider').trim();const n=Math.max(0,Number(err?.cooldownSeconds||err?.resetAfterSeconds||err?.retryAfter||0)||0);if(n>0){const m=Math.floor(n/60),s=Math.ceil(n%60),wait=m?`${m} min${m===1?'':'s'}${s?` ${s} sec`:''}`:`${s} sec`;return`${provider} vision capacity is temporarily reached. ARIA stopped safely so nothing was changed. Try again in about ${wait}.`}return`${provider} vision capacity is temporarily reached. ARIA stopped safely so nothing was changed. Try again when the limit resets.`}
function errorResult(err){const code=err?.code||'SCAN_FAILED',rate=code==='AI_RATE_LIMIT';return{error:{stage:err?.stage||'scan',code,message:rate?`${String(err?.provider||'AI vision provider')} rate limit reached.`:(err?.message||'Scan failed.'),userMessage:rate?rateLimitMessage(err):(err?.userMessage||'ARIA could not safely complete this scan. Nothing was changed.'),details:rate?{status:err?.status||null,provider_status:err?.providerStatus||null,provider:err?.provider||null,request_id:err?.requestId||null,attempt:err?.attempt||0,retry_after:err?.retryAfter??null,reset_after_seconds:err?.resetAfterSeconds??null,cooldown_seconds:err?.cooldownSeconds??null,rate_limit:err?.rateLimit||null}:null}}}
function decodeImage(value){return Buffer.from(String(value||'').replace(/^data:[^;]+;base64,/,'').replace(/\s/g,''),'base64')}
async function saveEvidence(client,jobId,orgId,imageBase64,hash){const buffer=decodeImage(imageBase64);if(!buffer.length||buffer.length>4000000)throw Object.assign(new Error('Prepared scan image is invalid or too large.'),{code:'INVALID_IMAGE'});const q=await client.query(`INSERT INTO scan_evidence(organization_id,scan_job_id,mime_type,image_hash,image_data) VALUES($1,$2,'image/jpeg',$3,$4) ON CONFLICT(scan_job_id) DO UPDATE SET image_hash=EXCLUDED.image_hash,image_data=EXCLUDED.image_data,mime_type=EXCLUDED.mime_type RETURNING id`,[orgId,jobId,hash,buffer]);return q.rows[0]?.id||null}
async function loadScanLearning(orgId){try{const q=await pool.query(`WITH g AS(SELECT 'global' scope,learning_type,learning_key,value,confidence,example_count FROM aria_global_learning WHERE active=true AND learning_type IN('ocr_name_visual_confusion','ocr_phone_digit_confusion') ORDER BY confidence DESC,example_count DESC,updated_at DESC LIMIT 24),o AS(SELECT 'organization' scope,learning_type,learning_key,value,confidence,1::int example_count FROM aria_learning WHERE organization_id=$1 AND active=true AND learning_domain='scan' AND learning_context='scan_extraction' AND scope_level='organization' ORDER BY confidence DESC,updated_at DESC LIMIT 24) SELECT * FROM g UNION ALL SELECT * FROM o`,[orgId]);return q.rows}catch(err){console.warn('[SCAN_LEARNING] Could not load learning hints:',err?.message||err);return[]}}
function phoneRecords(person){return(Array.isArray(person.phones)?person.phones:person.phone?[person.phone]:[]).slice(0,2).map((normalized,i)=>({raw:(Array.isArray(person.rawPhones)?person.rawPhones[i]:i===0?person.rawPhone:null)||normalized,normalized,source:'scan',index:i+1}))}
async function touchRecognizedPerson(client,orgId,jobId,person,decision){const id=decision.best_candidate_id;if(!id)return null;const payload={observed_name:person.raw_name||person.name||null,observed_phones:person.rawPhones||person.phones||[],normalized_phones:person.phones||[],row_number:person.row_number,scan_job_id:jobId,identity_match:decision.identity_match||'none',field_review_reasons:decision.field_review_reasons||[]};await client.query(`UPDATE people SET last_scan_job_id=$2,metadata=metadata||jsonb_build_object('last_scan_observation',$3::jsonb),updated_at=NOW() WHERE organization_id=$1 AND id=$4`,[orgId,jobId,JSON.stringify(payload),id]);return{id,name:decision.extracted_name,row_number:person.row_number}}
async function createPerson(client,orgId,jobId,actorId,programName,person,visionProvider=null){const phones=phoneRecords(person),metadata={scan_pipeline_version:SCAN_PIPELINE_VERSION,honorific:person.honorific||null,row_number:person.row_number,model_row_number:person.model_row_number??null,scan_evidence_job_id:jobId,vision_provider:visionProvider||null,phone_numbers:phones,raw_name:person.raw_name||null,raw_phones:person.rawPhones||[],extraction_review_reasons:person.extraction_review_reasons||[],name_evidence:person.name_evidence??null,phone_evidence:person.phone_evidence??null,pair_evidence:person.pair_evidence??null,name_confidence:person.name_confidence??null,phone_confidence:person.phone_confidence??null,pair_confidence:person.pair_confidence??null,model_confidence:person.model_confidence??null};const type=['regular','returning','familiar_face'].includes(person.relationship_stage)?'member':'visitor',q=await client.query(`INSERT INTO people(organization_id,first_name,last_name,display_name,phone,phone_numbers,type,status,confidence,source,created_by,last_scan_job_id,living_truth,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,'active',$8,'scan',$9,$10,$11,$12) RETURNING id,display_name,phone,phone_numbers,type`,[orgId,person.first_name,person.last_name,person.display_name,person.phone,JSON.stringify(phones),type,person.confidence??null,actorId,jobId,JSON.stringify({status:'alive',source:'scan',updated_at:new Date().toISOString()}),JSON.stringify(metadata)]);return q.rows[0]}
function reviewFallback(person,decision){return{status:'needs_decision',extracted_name:person.name,display_name:person.name,extracted_phone:person.phone,extracted_phones:person.phones||[],raw_phones:person.rawPhones||[],row_number:person.row_number,reasons:decision?.field_review_reasons||['identity_needs_decision'],reason:decision?.reason||'ARIA found evidence that needs your decision.',suggestion:'Check the original register and confirm or correct the information.',name_alternatives:person.name_alternatives||[],name_evidence:person.name_evidence??null,phone_evidence:person.phone_evidence??null,pair_evidence:person.pair_evidence??null,confidence:person.confidence??null,name_confidence:person.name_confidence??null,phone_confidence:person.phone_confidence??null,pair_confidence:person.pair_confidence??null,model_confidence:person.model_confidence??null,phone_flags:person.phone_flags||[],model_row_number:person.model_row_number??null,row_number_source:person.row_number_source||'extraction_order'}}
async function failJob(jobId,err,startTime,attempt=0){const e=errorResult(err);try{await updateJobState(null,jobId,INTERNAL_STATES.FAILED,'failed',e,attempt||err?.attempt||0,err?.provider||null,startTime)}catch(x){console.error('[SCAN] Failed to persist terminal state:',x?.message||x)}return e}
export async function processVisionJob(jobId,imageBase64,orgId,programName,options={}){
 const{evaluation=false,registerMode='complete',actorId=null}=options,startTime=Date.now();let client=null,transactionOpen=false,committed=false;
 try{
  if(!evaluation)await updateJobState(null,jobId,INTERNAL_STATES.ANALYSING,'preparing_image',null,0,null,startTime);
  const hash=crypto.createHash('sha256').update(imageBase64).digest('hex');let evidenceId=null;
  if(!evaluation){client=await pool.connect();await client.query('BEGIN');transactionOpen=true;evidenceId=await saveEvidence(client,jobId,orgId,imageBase64,hash);await client.query(`UPDATE scan_jobs SET image_hash=$1,started_at=COALESCE(started_at,NOW()),heartbeat=NOW(),last_progress_at=NOW() WHERE id=$2 AND organization_id=$3`,[hash,jobId,orgId]);await client.query('COMMIT');transactionOpen=false;client.release();client=null}
  if(!evaluation)await updateJobState(null,jobId,INTERNAL_STATES.EXTRACTING,'understanding_page',null,0,null,startTime);
  const scanLearning=await loadScanLearning(orgId);let vision;
  try{vision=await callVisionWithRetry(imageBase64,null,progress=>{if(!evaluation)pool.query(`UPDATE scan_jobs SET status=$1,progress=$2,heartbeat=NOW(),last_progress_at=NOW() WHERE id=$3`,[dbStatusFromInternal(INTERNAL_STATES.EXTRACTING),progress,jobId]).catch(()=>{})},{organization_id:orgId,job_id:jobId,purpose:'scan',prompt_version:SCAN_PIPELINE_VERSION,evaluation,scanLearning})}catch(err){return await failJob(jobId,{...err,stage:'ai_request',provider:err?.provider||null},startTime,err?.attempt||0)}
  const rawContent=vision?.data?.choices?.[0]?.message?.content;if(typeof rawContent!=='string'||!rawContent.trim())return await failJob(jobId,Object.assign(new Error('Vision returned no content.'),{code:'EMPTY_AI_RESPONSE',stage:'ai_request',userMessage:'ARIA could not safely read the register. Nothing was changed.'}),startTime,1);
  if(!evaluation)await updateJobState(null,jobId,INTERNAL_STATES.VALIDATING,'validating_extraction',null,1,vision.provider||null,startTime);
  const validation=validateScanOutput(rawContent);if(!validation.valid)return await failJob(jobId,Object.assign(Error(validation.error),{code:'INVALID_AI_RESPONSE',stage:'parse_json',userMessage:'ARIA could not safely understand the register. Nothing was changed.'}),startTime,1);if(evaluation)return validation;
  const context=buildScanContext(validation.people,scanLearning,{registerMode,programName});
  await updateJobState(null,jobId,INTERNAL_STATES.MATCHING,'resolving_identity',null,1,vision.provider||null,startTime);
  client=await pool.connect();await client.query('BEGIN');transactionOpen=true;await client.query(`SELECT pg_advisory_xact_lock(hashtextextended('nyeocare:identity:'||$1,0))`,[orgId]);
  const identity=await handleScanEvent(validation.people,orgId,jobId,client,context),newPeople=[],matchedPeople=[],reviewItems=[],events=[];
  await updateJobState(client,jobId,INTERNAL_STATES.SAVING,'saving_truth',null,1,vision.provider||null,startTime);
  for(const person of validation.people){
   const decision=identity.decisions.find(d=>Number(d.row_number)===Number(person.row_number))||null,fieldReasons=[...new Set([...(person.extraction_review_reasons||[]),...(decision?.field_review_reasons||[])])],needsIdentityReview=!decision||decision.status==='conflict'||decision.status==='needs_decision';
   if(needsIdentityReview||fieldReasons.length){const review=validation.needsReview.find(x=>Number(x.row_number)===Number(person.row_number))||reviewFallback(person,decision),reviewId=await createScanReview(client,{organizationId:orgId,scanJobId:jobId,scanEvidenceId:evidenceId,actorId,programName,person,decision:decision||{status:'needs_decision'},review});reviewItems.push({id:reviewId,name:person.name,phone:person.phone,phones:person.phones||[],reason:review.reason,suggestion:review.suggestion,reasons:[...new Set([...(review.reasons||[]),...fieldReasons])],row_number:person.row_number,candidate_ids:decision?.candidate_ids||[],candidates:decision?.candidates||[]});continue}
   if(decision?.status==='alive'&&decision.best_candidate_id){const matched=await touchRecognizedPerson(client,orgId,jobId,person,decision);if(matched)matchedPeople.push(matched);continue}
   const created=await createPerson(client,orgId,jobId,actorId,programName,person,vision.provider||null);newPeople.push({id:created.id,name:created.display_name,type:created.type,phones:created.phone_numbers||[],row_number:person.row_number});const event=await emitAriaEvent({organizationId:orgId,personId:created.id,type:'PERSON_CREATED',source:'scan',actorId,metadata:{jobId,programName,pipeline_version:SCAN_PIPELINE_VERSION},eventKey:`scan:${jobId}:person:${created.id}`},client);if(event)events.push(event)
  }
  const result={status:'ok',scan_pipeline_version:SCAN_PIPELINE_VERSION,new_members:newPeople.length,recognized:matchedPeople.length,needs_review:reviewItems,needs_review_count:reviewItems.length,rejected:validation.rejected,total_extracted:validation.total_extracted,total_valid:validation.total_valid,register_mode:registerMode,verification:{accepted:newPeople.length+matchedPeople.length,rejected:validation.rejected.length,review:reviewItems.length,passes:vision.verification?.passes||1,mode:vision.verification?.mode||'single_pass_rate_aware_vision'},evidence:{available:true,job_id:jobId,evidence_id:evidenceId},layout:{provider:'qwen-full-page-observation',rows:validation.total_extracted},context:{version:context.version,row_count:context.row_count,shared_phone_groups:context.shared_phone_groups.length,repeated_name_groups:context.repeated_name_groups.length,learning_hints:context.learning_hints.length},learning:{global_hints:scanLearning.filter(x=>x.scope==='global').length,organization_hints:scanLearning.filter(x=>x.scope==='organization').length},summary:`ARIA found ${validation.total_extracted} people: ${matchedPeople.length} existing recognized, ${newPeople.length} new remembered, and ${reviewItems.length} need your attention.`};
  await updateJobState(client,jobId,INTERNAL_STATES.COMPLETED,'complete',result,1,vision.provider||null,startTime);await client.query('COMMIT');transactionOpen=false;client.release();client=null;committed=true;if(events.length)Promise.allSettled(events.map(event=>directAriaEvent(event))).catch(()=>{});if(reviewItems.length){const{emitAriaEvent}=await import('./aria/eventEmitter');const reviewEvent=await emitAriaEvent({organizationId:orgId,type:'SCAN_REVIEW_REQUIRED',source:'scan',actorId,metadata:{job_id:jobId,review_count:reviewItems.length,program_name:programName},eventKey:`scan:${jobId}:review_required`});if(reviewEvent)Promise.resolve(directAriaEvent(reviewEvent)).catch(()=>{})}return result;
 }catch(err){if(client&&transactionOpen)try{await client.query('ROLLBACK')}catch{}if(client)try{client.release()}catch{}const e=errorResult({stage:'database_save',code:err?.code||'DB_TRANSACTION_ERROR',message:err?.message||'Database transaction failed',userMessage:'ARIA could not save the scan safely. Nothing was changed.'});if(!committed)try{await updateJobState(null,jobId,INTERNAL_STATES.FAILED,'failed',e,1,null,startTime)}catch(x){console.error('[SCAN] Terminal DB state failed:',x?.message||x)}return e}
}
